### ISSUE TITLE
support callback function on "start", "process", "finish","error" event

### ISSUE THREAD

**Issue by alphabetaxz** [kkroening/ffmpeg-python#100]

**Comment by kkroening** [comment]
What would this look like, and more importantly why?

This is all supported with standard python:
```python
my_start_func()
try:
    ffmpeg.input('in.mp4').output('out.mp4').run()
    my_finish_func()
except ffmpeg.Error as e:
    my_error_func(e)
```

Why reinvent the wheel?

**Comment by kkroening** [comment]
@alphabetaxz If you add a description and a convincing argument I may reopen this. Closing for now.
