### ISSUE TITLE
Simple stream selection?

### ISSUE THREAD

**Issue by whichken** [kkroening/ffmpeg-python#102]
I'm trying to do some simple stream selection. Using ffmpeg directly, I'd use the map option. However, when trying to do this using ffmpeg-python, I can't seem to get it correct. The map argument is getting put into a bracket, which doesn't work.

```
>>> import ffmpeg
>>> infile = ffmpeg.input('test.mkv')
>>> stream = infile['1']
>>> outfile = ffmpeg.output(stream, 'test-out.mkv')
>>> ffmpeg.compile(outfile)
['ffmpeg', '-i', 'test.mkv', '-map', '[0:1]', 'test-out.mkv']
```
This fails with the error `Output with label '0:1' does not exist in any defined filter graph, or was already used elsewhere.`

What is the proper way to do stream selection when you don't need complex video graphs?

**Comment by alphabetaxz** [comment]
what you need may be:  infile[0:'v']

**Comment by whichken** [comment]
That throws an exception.

```
>>> stream = infile[0:'v']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/project/env/lib/python3.5/site-packages/ffmpeg/nodes.py", line 63, in __getitem__
    raise TypeError("Expected string index (e.g. 'a'); got {!r}".format(index))
TypeError: Expected string index (e.g. 'a'); got slice(0, 'v', None)
```

**Comment by alphabetaxz** [comment]
sorry, i misunderstand what you mean, if you only want to select some streams from source to output without any filters ,i think you can use "map" option of ffmpeg, eg:

infile = ffmpeg.input('test.mkv')
outfile = ffmpeg.output(infile, 'test-out.mkv', map="0:v")
ffmpeg.run(outfile)

**Comment by alphabetaxz** [comment]
sorry , about this

**Comment by kkroening** [comment]
@whichken What's the raw ffmpeg command you're trying to emulate with `ffmpeg-python`?

**Comment by kkroening** [comment]
Also, the `[]` operator should probably be able to accept integers (in addition to strings, as currently supported).

**Comment by kkroening** [comment]
Or perhaps eventually this shorthand would make things simpler:
```python
infile = ffmpeg.input('test'.mk4')
outfile = ffmpeg.output(infile[[1, 2]], 'test-out.mkv')
```
or fluently:
```
(
    ffmpeg
    .input('test.mk4')
    [[1, 2]]
    .output('test-out.mkv')
    .run()
)
```

The `[]` operator would basically take either a single identifier (e.g. `['v']`) or a list of identifiers (e.g. `[[1, 2]]`). This is similar to how a library like Pandas operates.

**Comment by whichken** [comment]
All those options look great. 

I was going to suggest that the produced -map [0:1] was a bug, but I'm not familiar enough with ffmpeg to know if that was some other format that I was unfamiliar with.

Let me know if I can help out at all.

**Comment by kkroening** [comment]
#103 should fix this.

@whichken If you get a chance, let me know if #103 fixes this for you.

Regardless, I'll merge it in the next day or so if I don't hear back.

**Comment by faroit** [comment]
@kkroening 

regarding:

`ffmpeg -i test.mkv -map 0:1 -map 0:2 out.mkv`

> Ok yeah, we need to figure out a way to support this. AFAICT there's no way to do this currently, or at least not in any reasonable manner.

is there a workaround for it now?

**Comment by emrahgunduz** [comment]
You can try something like this
```python
video_a = ffmpeg.input( file_a )
video_b = ffmpeg.input( file_b )
out = ffmpeg.output( video_a.video, video_b.audio, to_file )
```
This will generate `-map 0:v -map 1:a` in your argument list.
