### ISSUE TITLE
.global_args works not as expected

### ISSUE THREAD

**Issue by Nitaym** [kkroening/ffmpeg-python#106]
get_args() puts the global_args after the output args, meaning it's marked as "trailing commands" by ffmpeg

This is what I'm trying to achieve
`ffmpeg -i rtsp://192.168.1.22:554/default -preset ultrafast -tune zerolatency -b 900k -f h264 -`

With this line
```
        out, err, subproc = (
            ffmpeg
            .input('rtsp://%s:554/default' % ip)
            .output('-', format='h264')#, pix_fmt='yuv420p')
            .global_args('-preset')
            .global_args('ultrafast')
            .global_args('-tune')
            .global_args('zerolatency')
            .global_args('-b')
            .global_args('900k')
            .run(capture_stdout=True, wait=False)
        )

```

But I got this instead:
`ffmpeg -i rtsp://192.168.1.22:554/default -f h264 - -preset ultrafast -tune zerolatency -b 900k`

I tried putting the .global_args after .input but got this exception:

> AttributeError: 'FilterableStream' object has no attribute 'global_args'

Is this intended behaviour?

**Comment by kkroening** [comment]
It sounds like you want these arguments to apply to a particular output. In that case, pass them as parameters to `.output`:
```python
(
    ffmpeg
    .input('rtsp://%s:554/default' % ip)
    .output('-', format='h264', preset='ultrafast', tune='zerolatency', b='900k')
    ...
)
```
