### ISSUE TITLE
coding problem, looking for help!

### ISSUE THREAD

**Issue by lbc001** [kkroening/ffmpeg-python#107]
hello, I am doing something like this:
```
    split = ffmpeg.input("test.mp4").split()
    base_stream = split[0].trim(start_frame=0, end_frame=100)
    overlay_stream = split[1].trim(start_frame=0, end_frame=100)
    overlay_stream = overlay_stream.crop(600, 100, 200, 200).filter("boxblur", 10)
    base_stream.overlay(overlay_stream, x=600, y=100).output("output.mp4").run()
````
now I need crop and boxblur on different area.for example, on 1 frame work on (600, 100, 200, 200), on 2 frame work on (600, 150, 150, 150)..etc.I have tried many times but all failed in compile. How can i implement this?

**Comment by kkroening** [comment]
Note that in place of numerical values (e.g. `600`, `100`, etc) you can pass strings that map to ffmpeg expressions (e.g. `100+t`). See the [ffmpeg crop filter](https://ffmpeg.org/ffmpeg-filters.html#crop) documentation for the variables that are available, as well as the [ffmpeg expression evaluation](https://www.ffmpeg.org/ffmpeg-all.html#Expression-Evaluation) documentation.
