### ISSUE TITLE
how can create video from list of images

### ISSUE THREAD

**Issue by prajwal-mulkalwar** [kkroening/ffmpeg-python#109]
i have list 
imglist = ['path/to/img1','path/to/img2','path/to/img3']
I would like to know  if i can use this list to create videos.

**Comment by prajwal-mulkalwar** [comment]
hi 
'/path/to/jpegs/*.jpg' ->this will give me all images there are. what I'm Trying to do is use only selective images. so have list in python for selected images, want to make videos from those only

**Comment by 153957** [comment]
Would it be a problem to simply move/copy/symlink those image you do want into a new directory and points ffmpeg to that directory? it might still be possible to do it with selective images, just create one input per image, and concat them all.. but that seems impractical.

**Comment by kkroening** [comment]
Thanks @153957.
