### ISSUE TITLE
Unclear way to specify output file parameters

### ISSUE THREAD

**Issue by Depaulicious** [kkroening/ffmpeg-python#11]
Hi,
I'm noticing that there's no clear way to specify how the output formats should be specified.
I need apply some filters to different streams (scale them) and output multiple formats at the same time.

I need to specify the output codecs and quality parameters, and I'm uncertain on how that can be done.

**Comment by kkroening** [comment]
I've been meaning to add this. It'll most likely be a set of kwargs on the `output` function:
```
def output(parent_node, **kwargs):
```

Then the kwargs will be handled in `_get_output_args` of `_run.py`
```
def _get_output_args(node, stream_name_map):
    args = []
    if node._name != merge_outputs.__name__:
        stream_name = stream_name_map[node._parents[0]]
        if stream_name != '[0]':
            args += ['-map', stream_name]
        if node._name == output.__name__:
            args += [node._kwargs['filename']]
            # TODO: handle additional output kwargs.
        else:
            assert False, 'Unsupported output node: {}'.format(node)
    return args
```

Feel free to start implementing this, otherwise I'll get to it soon.

**Comment by Depaulicious** [comment]
I'll be working again on Friday, I'll look at it.
This wouldn't help with multiple outputs though :/

I mean one stream with multiple outputs in the same command line

**Comment by kkroening** [comment]
It should work with multiple outputs:
```
out1 = parent.output(
    'pipe:0',
    format='rawvideo',
    pixel_format='rgb24',
    video_size=(width, height),
    framerate=10
)
out2 = parent.output('out.mp4')
out = ffmpeg.merge_outputs(out1, out2)
```
`merge_outputs` means that both outputs should be included in the ffmpeg command. (The name might be confusing - I'm open to suggestion on a better name)

**Comment by kkroening** [comment]
There are a ton of input/output options in ffmpeg. It might be hard to support _all_ of them off the bat. I'll probably add the most common ones first and then generalize later. Are there any in particular that you're looking for (e.g. `-ss pos`?

**Comment by kkroening** [comment]
Okay, I think this is working. Check out the [test example](https://github.com/kkroening/ffmpeg-python/pull/14/files#diff-bd9c29fd57f322529a9d5d7fd430e0baR180) on the `io-flags` branch:
```
out = (ffmpeg
     .input('pipe:0', format='rawvideo', pixel_format='rgb24', video_size=(width, height), framerate=10)
     .trim(start_frame=start_frame)
     .output('pipe:1', format='rawvideo')
)
```
I'll merge the PR soon.

**Comment by kkroening** [comment]
PR merged. If this works for you let me know and I'll close the issue

**Comment by Depaulicious** [comment]
Awesome, I'll try it later this afternoon. I guess `merge_outputs` is fine, I'll thinking of any other synonym that may express that better.

**Comment by Depaulicious** [comment]
I'm not sure what "pipe:#" means, is it `pipe:0 == stdin`, `pipe:1 == stdout`, `pipe:2 == stderr`, etc. or is it specific to this implementation?

**Comment by agosto-karlkroening** [comment]
>  is it pipe:0 == stdin, pipe:1 == stdout, pipe:2 == stderr, etc. 

Yes - standard ffmpeg arguments - just handing it to ffmpeg verbatim

**Comment by kkroening** [comment]
https://www.ffmpeg.org/ffmpeg-protocols.html#pipe

**Comment by Depaulicious** [comment]
I tested it a bit late, it works fine.

**Comment by kkroening** [comment]
👍
