### ISSUE TITLE
Adding Metadata

### ISSUE THREAD

**Issue by Matttman** [kkroening/ffmpeg-python#112]
I am trying to find a way to add metadata to the output. Using ffmpeg from the command line I would use something like `-metadata title="Title"` . I couldn't find anything relating to this in the ffmpeg-python docs. I tried a few different methods, using global_args and output kwargs and I wasn't able to get it to work, usually getting an error like the following.

```
Unrecognized option 'metadata title="test title"
Error splitting the argument list: Option not found
```

Here's an example of a full command using ffmpeg.
```
ffmpeg -i 1-00.30.mp4 -vcodec copy -acodec copy -scodec copy -metadata title="Sample Title" 1-00.30_copy.mp4
```
Any help would be appreciated.

**Comment by Matttman** [comment]
I Solved it by using the output kwargs and using metadata='title=Example Title'.
```python
title =' Example Title'
out = (
    ffmpeg
    .input(infile)
    .output(outfile, metadata='title=' + title)
)
```

**Comment by BigSully** [comment]
While another question arise, how do we add two or more metadata? As does the following terminal commands:
ffmpeg -i "concat:file1.mp3|file2.mp3" -metadata title="new title"  -metadata artist="foo bar" -acodec copy output.mp3

**Comment by ianhomer** [comment]
To set multiple metadata arguments you can cheat a little by using metadata specifiers in a kwargs argument ...
` 
**{
  'metadata':'title=My Title',
  'metadata:':'artist=Me',
  'metadata:g':'album=X',
}
`
A little ugly, but I can set 3 metadata keys using this technique.

**Comment by BigSully** [comment]
> To set [multiple metadata arguments](https://ffmpeg.org/ffmpeg-all.html#Metadata-1) you can cheat a little by using metadata specifiers in a kwargs argument ...
> ` **{ 'metadata':'title=My Title', 'metadata:':'artist=Me', 'metadata:g':'album=X', }`
> A little ugly, but I can set 3 metadata keys using this technique.

It works, thanks.

**Comment by ianhomer** [comment]
A little cleaner, it seems I can do ...
`
 {
            'metadata:g:0':"title=My Title",
            'metadata:g:1':"artist=Me",
            'metadata:g:2':"album=X",
            'metadata:g:3':"year=2019",
        }
`
which hopefully means I can add as many metadata items as I need.  The index - 0,1,2,3 - seems to be just ignored my ffmpeg as they are all global metadata items, but at least give us unique key values in the dictionary object that the ffmpeg wrapper uses for building up the ffmpeg arguments.

**Comment by BigSully** [comment]
> A little cleaner, it seems I can do ...
> `{ 'metadata:g:0':"title=My Title", 'metadata:g:1':"artist=Me", 'metadata:g:2':"album=X", 'metadata:g:3':"year=2019", }`
> which hopefully means I can add as many metadata items as I need. The index - 0,1,2,3 - seems to be just ignored my ffmpeg as they are all global metadata items, but at least give us unique key values in the dictionary object that the ffmpeg wrapper uses for building up the ffmpeg arguments.

Awesome. I'd never find this trick by looking those documents. How did you find this trick? By reading source code?

**Comment by AzazelHD** [comment]
Hi guys. Just a little question. I know u can pass **metadata_dict as argument to set multiple metadata as u stated before, but why the keyword ``metadata`` isnt needed?

**Comment by AlimusSifar** [comment]
> Hi guys. Just a little question. I know u can pass `**metadata_dict` as argument to set multiple metadata as u stated before, but why the keyword `metadata` isnt needed?
> 
> ```
> def test(src, dst, **kwargs):
>     (
>         ffmpeg
>             .input(src).audio
>             .output(f'{dst}.mp3', **kwargs)
>             .overwrite_output()
>             .run()
>     )
> ```
> 
> With this small function, im trying to call it like this: `test("song.mp3", "Test1", map_metadata=-1, metadata={'metadata:g:0': f'title=hello', 'metadata:g:1': f'date=2000'})`
> 
> But it is not working. However, if i remove the `metadata` keyword and i call it like: `test("song.mp3", "Test1", map_metadata=-1, **{'metadata:g:0': f'title=hello', 'metadata:g:1': f'date=2000'})` It works.
> 
> Can someone explain me please?

@AzazelHD It's working because of `dictionary unpacking` feature. Watch 1 or 2 short videos on list/dictiona

**Comment by AlimusSifar** [comment]
> Can someone explain me please?

@AzazelHD It works because of `dictionary unpacking` feature. Watch 1 or 2 short videos on list/dictionary unpacking and you'll understand that easily.

In short:
```python
def func(**kwargs: "dict | None"):
    print(kwargs)
```

The `func` function takes only `key-value` arguments e.g. a=1, b=2 and stores them in the parameter `kwargs`.
because of the `**` before the parameter, `kwargs` puts all the `key-value`s as the dictionary key and value.

So, calling `func(a=1, b=2)` will form `kwargs={"a":1, "b":2}` inside the function.
> Packing all the keys-values into a dictionary.

Similarly, calling `func(**{"a":1, "b":2})` will form `func(a=1, b=2)` as the arguments.
> Unpacking all the keys-values from a dictionary.

\*also similar for `list unpacking` e.g.:
```python
def func2(*args: "list | None"):
    print(args)
```
---
For not working with `metadata={key: value}` because, inside the function forms:
```python
kwargs={
    "metadata": {key: value}
}
```
by using `**{key: value, ...: ...}`, inside the function forms:
```python
kwargs={
    key: value,
    ...: ...
}
```
I hope you got something.

**Comment by pengzhendong** [comment]
> A little cleaner, it seems I can do ... `{ 'metadata:g:0':"title=My Title", 'metadata:g:1':"artist=Me", 'metadata:g:2':"album=X", 'metadata:g:3':"year=2019", }` which hopefully means I can add as many metadata items as I need. The index - 0,1,2,3 - seems to be just ignored my ffmpeg as they are all global metadata items, but at least give us unique key values in the dictionary object that the ffmpeg wrapper uses for building up the ffmpeg arguments.

How to set multiple metadata items of `metadata:s:s:0`?

**Comment by me-kell** [comment]
To make sure the index is unique I find the following useful:
```python
metadata_list = ["title=My Title", "artist=Me", "album=X", "year=2019",]
metadata_dict = {f"metadata:g:{i}": e for i, e in enumerate(metadata_list)}
out, err = (
    ffmpeg
        .input(infile)
        .output(outfile, **metadata_dict)
)
```

**Comment by ruanimal** [comment]
> > A little cleaner, it seems I can do ... `{ 'metadata:g:0':"title=My Title", 'metadata:g:1':"artist=Me", 'metadata:g:2':"album=X", 'metadata:g:3':"year=2019", }` which hopefully means I can add as many metadata items as I need. The index - 0,1,2,3 - seems to be just ignored my ffmpeg as they are all global metadata items, but at least give us unique key values in the dictionary object that the ffmpeg wrapper uses for building up the ffmpeg arguments.
> 
> How to set multiple metadata items of `metadata:s:s:0`?

so, how to set title and language for subtitle? 
`-metadata:s:s:0 language=eng -metadata:s:s:0 title="English Subtitle"`
