### ISSUE TITLE
How to know what the error is ?

### ISSUE THREAD

**Issue by jenniferSun27** [kkroening/ffmpeg-python#115]
I run this:
```python
        stream = ffmpeg.input(vFullFilename)
        stream = stream.hflip()
        stream = stream.output(aFullFilename)
        x = stream.get_args()
        print(x)
        stream = stream.run()
```
It shows:
![image](https://user-images.githubusercontent.com/12219153/44508784-2fd35980-a6e2-11e8-9e69-3794d91a06e5.png)
There's garbled in the output, how to know what's wrong with the code?

Thanks.

**Comment by kkroening** [comment]
What's your OS and language/locale?

**Comment by kkroening** [comment]
Is this still an issue? If not I'm closing it.

**Comment by Bagusa4** [comment]
I guess this happened on windows because he doesn't set the path variable for "ffmpeg" command, because I have the same problem. 

How about if the FFmpeg library is also included in the "python-ffmpeg" package?
