### ISSUE TITLE
The system can't find the specified file

### ISSUE THREAD

**Issue by konniskatt** [kkroening/ffmpeg-python#119]
I am having this error whe I try to use ffmpeg-python:
Traceback (most recent call last):
  File "C:\Users\nicol\Desktop\ffmpegpy.py", line 6, in <module>
    .output('output.mp4')
  File "C:\Program Files\Python36\lib\site-packages\ffmpeg\_run.py", line 208, in run
    p = subprocess.Popen(args, stdin=stdin_stream, stdout=stdout_stream, stderr=stderr_stream)
  File "C:\Program Files\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
                                                          (The system can't find the specified file)
Any idea why isn't working?
Btw, there is the script that I try to run:

import ffmpeg
(
    ffmpeg
    .input('audiosurf.mp4')
    .hflip()
    .output('output.mp4')
    .run()
)
I taked the code from the ffmepeg-python README.md

**Comment by bstojkovic** [comment]
I'm getting the same error. Did you fix this?

**Comment by bstojkovic** [comment]
I put `ffmpeg.exe` in `C:\ffmpeg`. In system environment variable `PATH`, I added `C:\ffmpeg`, prior to posting my comment, but I was still getting the error.

I'm OK with specifying the path to ffmpeg however. Thank you for reply.
