### ISSUE TITLE
 escape_chars fails in filter() and filter_() (and possibly elsewhere...)

### ISSUE THREAD

**Issue by laurentalacoque** [kkroening/ffmpeg-python#124]
On Win32 systems, the `escape_chars` function turns berserk and hyper-escapes some symbols.
This result in an invalid parameter in `ffmpeg` and fails to run.

## Testcase
``` python
import ffmpeg
testcase = ffmpeg.input("Wildlife.wmv").filter('scale',"320:-2").output("wontwork.mp4")
print(testcase.compile())
testcase.run()
```

## Output

``` python
['ffmpeg', '-i', 'Wildlife.wmv', '-filter_complex', '[0]scale=320\\\\\\\\\\\\:-2[s0]', '-map', '[s0]', 'wontwork.mp4']
```

```
<some ffmpeg output>
[Parsed_scale_0 @ 00000000005c6c80] Invalid size '320\:-2'
[AVFilterGraph @ 00000000028c6500] Error initializing filter 'scale' with args '320\\\:-2'
Error initializing complex filters.
Invalid argument
```
## Discussion

- The colon `:` is escaped by `escape_chars` although it shouldn't (at least on win32 systems).
- Saving `testbench.compile()` to a `.bat` file, manually removing the six `\` and running the command solves the issue.
- The reason between the fact that there are 12 `\` is unclear (would default to 6 passed to Popen, then 3 when parsed by ffmpeg)

## Configuration
- Windows 7
- Python 3.6.3 :: Anaconda custom (64-bit)
- ffmpeg-python version 0.1.16
- ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers

**Comment by kkroening** [comment]
```diff
-ffmpeg.input("Wildlife.wmv").filter('scale',"320:-2").output("wontwork.mp4")
+ffmpeg.input("Wildlife.wmv").filter('scale', 320, -2).output("wontwork.mp4")
```
The reason there are so many `\` characters is because of ffmpeg's recursively nested escaping rules. Try using the `drawtext` filter manually from the command line and see how many backslash escapes it takes to draw the text "`\`" over a video. It's intended behavior - see the [escape_chars test cases](https://github.com/kkroening/ffmpeg-python/blob/master/ffmpeg/tests/test_ffmpeg.py#L26).

**Comment by laurentalacoque** [comment]
Understood!
This is more of a `filter` documentation problem to me then.
Thanks for your answer!

**Comment by kkroening** [comment]
Thanks for the feedback about documentation. We'll keep that in mind as the documentation is improved.

**Comment by kkroening** [comment]
Also big props for such a well-written ticket. I appreciate the time you spent keeping the ticket organized so that it was easy to see what's going on.
