### ISSUE TITLE
How to provide an option like "-an" that doesn't have an argument

### ISSUE THREAD

**Issue by cxrodgers** [kkroening/ffmpeg-python#136]
First of all, thanks so much for this really cool package!

This is probably a simple question. I just want to add an "-an" to my parameters.

Here's my current call:

    ffmpeg.input(new_filename).output(h264_stream, vcodec='copy', **{'bsf:v': h264_mp4toannexb'}).compile()

[u'ffmpeg',
 u'-i',
 NEW_FILENAME,
 u'-bsf:v',
 u'h264_mp4toannexb',
 u'-vcodec',
 u'copy',
H264_STREAM]

I just want to add an '-an' to the list, somewhere after the input, to remove audio. I tried this:

    ffmpeg.input(new_filename).output(h264_stream, vcodec='copy', **{'bsf:v': h264_mp4toannexb', 'an': ''}).compile()

And it's almost right, but there's an extra empty string that confuses ffmpeg.
[u'ffmpeg',
 u'-i',
 NEW_FILENAME,
 u'-an',
 u'',
 u'-bsf:v',
 u'h264_mp4toannexb',
 u'-vcodec',
 u'copy',
 H264_STREAM]

    Unable to find a suitable output format for ''
    : Invalid argument

I would appreciate any tips about how to do this! Thanks!

**Comment by miabrahams** [comment]
For -an you can do  your_ffmpeg_stream['v'].run() to keep only the video stream.

**Comment by ritlew** [comment]
@cxrodgers @groupmsl I found a workaround. I just supply an argument like this: `an=None`.

**Comment by cxrodgers** [comment]
@ritlew Perfect, thanks!

**Comment by h3ct0r** [comment]
This must be on the wiki! Thanks @ritlew!

**Comment by dminGod** [comment]
> Is there a more generic way to do this (specify an option without an argument)? I'm trying to specify the "-re" flag to read the input at realtime speed ([https://trac.ffmpeg.org/wiki/StreamingGuide#The-reflag](url))
> 
> Thank you, Andy

I struggled with this as well.  for people looking to do the same thing -- Now "-re" needs to be the first thing even before the "-i" to work properly and I couldn't find anyway to get "-re" in the correct position

Finally, I did this :

```python
ffmpeg.input(...).output(...).run(cmd=["ffmpeg", "-re"])
```

lo and behold, it worked! : )
