### ISSUE TITLE
AttributeError: 'FilterableStream' object has no attribute 'map'

### ISSUE THREAD

**Issue by jlsalmon** [kkroening/ffmpeg-python#139]
I'm not 100% sure but I think something may have gotten messed up with the merge of #45 becuase in `0.1.16` there is no `map` function in `_ffmpeg.py` (nor in master). It looks like 0d95d9b58dd4fcb9dd424bdb4f3bf62629e9c3b6 may have been lost somehow.

I was all excited and looking forward to use it and it's not there :(

**Comment by mhoare** [comment]
this would be really useful to have back tbh - using output is a pain when trying to add audio before doing some more concats without extra audio...
