### ISSUE TITLE
Any way to use `silenceremove` with fmpeg-python

### ISSUE THREAD

**Issue by mnmistake** [kkroening/ffmpeg-python#141]
I need to take out the silence at my audio files, I need to trim if the pause in speech is less than -25dB 

I have somehitng like this (I know ffmpeg has this property silenceremove) can I use that with this libreary? thanks

```
ffmpeg
            .input(in_filename, **input_kwargs)
            .filter('silencedetect', n='-25dB', d=3)
            .output('-', format='s16le', acodec='pcm_s16le', ac=1, ar='16k')
            .overwrite_output()
            .compile()
```

Please someone label this as a question, no much docs around

**Comment by kkroening** [comment]
Probably. Best bet is to try it and find out.

**Comment by jtich** [comment]
@mnmistake Any luck getting the `silenceremove` filter working with this package?

**Comment by hankehly** [comment]
A little late to the party but for anyone who's reading this, there's an example handling silences here (does not use silenceremove however)
https://github.com/kkroening/ffmpeg-python/blob/master/examples/split_silence.py
