### ISSUE TITLE
HLS transport stream creation from python numpy arrays

### ISSUE THREAD

**Issue by Surya059** [kkroening/ffmpeg-python#142]
I am looking for a way to directly create transport stream segments for HLS live streaming from python.
Currently I am using skvideo ffmpeg writer to do that. Does FFMPEG Python directly provide an option?

**Comment by Surya059** [comment]
To clarify a little more, I am a stream of numpy arrays I get from a different server. And I need a way to pass this stream from Python to continuously create transport stream segments. And also update the m3u8(for hls) if possible

**Comment by kkroening** [comment]
That should be doable. I added [an example](https://github.com/kkroening/ffmpeg-python/tree/master/examples#tensorflow-streaming) that I think is similar to what you're trying to do. Replace the input/output args as desired.

And here's the detailed code with better error handling: https://github.com/kkroening/ffmpeg-python/blob/master/examples/tensorflow_stream.py

Let me know if that's what you're after.

**Comment by Surya059** [comment]
I was actually looking more insight into ffmpeg support HTTP live streaming. But the example gave a headstart,  I will post the solution once I am done. 

Thanks

**Comment by pollux77** [comment]
@Surya059 Hi, have you find the solution ? I'm looking a solution to broadcast video using ffmpeg through HTTP live streaming
