### ISSUE TITLE
The ffmpeg-numpy example can not display images

### ISSUE THREAD

**Issue by gzlock** [kkroening/ffmpeg-python#149]
![image](https://user-images.githubusercontent.com/2311740/49684890-0f0a0500-fb15-11e8-88f7-c5261a5a4e91.png)
![image](https://user-images.githubusercontent.com/2311740/49684894-16c9a980-fb15-11e8-8dd2-9a4327bb236d.png)
It can read the frames number from the video file, but do not display the images
env:
macOS Mojave
ffmpeg 4.1
python 3.7.1
Chrome and Safari do not display the images

**Comment by kkroening** [comment]
What's your jupyterlab version?

I've seen issues with widgets not rendering properly on certain combinations of python + jupyterlab versions that required reinstalling of the jupyterlab manager
