### ISSUE TITLE
tensorflow sample?

### ISSUE THREAD

**Issue by jlsalmon** [kkroening/ffmpeg-python#151]
I know this isn't really a python-ffmpeg question, but what kind of machine were you running the tensorflow_stream example on, and what kind of framerate were you getting? I'm using a g3s.xlarge instance (with a GPU) on AWS and I run it for 5 minutes and get maybe 5 seconds of output video.

**Comment by kkroening** [comment]
You need to set up tensorflow for GPU support. `pip install tensorflow-gpu` for starters. It was quite an annoying/involved process to get TF running with proper gpu support on my VM at the time and my notes are scattered on the topic (and probably outdated).

Next time I go through the setup I'll try to compile it as some sort of VM provisioning script (at some point). Reproducibility is king of computing.

In the meantime, if you figure out steps to get proper TF GPU support on your VM feel free to share notes here, and it'll be much appreciated.
