### ISSUE TITLE
Can't find file with ffmpeg.input()

### ISSUE THREAD

**Issue by tossorrow** [kkroening/ffmpeg-python#153]
```
import ffmpeg
import os

file1 = 'input.avi'
file2 = 'output.avi'
print(os.path.isfile(file1))   #True

stream = ffmpeg.input(file1)
stream = ffmpeg.hflip(stream)
stream = ffmpeg.output(stream, file2)
print(stream.get_args())
ffmpeg.run(stream)   #FileNotFoundError: [WinError 2] The system could not find the specified file.
```

 Here is the print:
```
True
['-i', 'input.avi', '-filter_complex', '[0]hflip[s0]', '-map', '[s0]', 'output.avi']
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
```

**Comment by kkroening** [comment]
Make sure ffmpeg is installed and on your system path. Note that ffmpeg-python does _not_ try to automatically install ffmpeg. It's simply a python _wrapper_ for ffmpeg, and it's up to you to make sure it's installed in whatever way makes sense for how you're using it.

**Comment by kkroening** [comment]
We should keep this in mind though, that users may see unexpected error messages if ffmpeg can't be found. It should probably either be in the docs, or print a more helpful error message. Thanks for reporting.

Please let me know if this fixes your issue.

**Comment by tossorrow** [comment]
Problem solved. Thank you for your help!
An error message like 'ffmpeg is not installed' cound be very helpful for beginners.

**Comment by gugarosa** [comment]
I agree! For a minute, I thought that this package would make ffmpeg avaliable behind the scenes. Not a problem to install it though, just pointing that a more informative message would be better.

**Comment by kkroening** [comment]
Thanks for the suggestion. I'll try to add a more helpful error message if I can find time. PRs are welcome as well.

**Comment by UweR70** [comment]
Is this still the case:
Note that ffmpeg-python does not try to automatically install ffmpeg.

I installed ffmpeg-python first
run in the error
installed than ffmpeg
run my python code and got the error that ffmpeg does not hat a ".input" function.

I was forced to unstall both and re-install ffmpeg.
But have now the same issue. "File not found"
But the file exists under the given path.

**Comment by OGreenwood672** [comment]
I had a similar issue,

I already had ffmpeg in my path, however was still getting the input function not found error when I ran my code.

SOLUTION: Add to the top of your file:
`import sys`
`sys.path.append(<LOCATION TO ffmpeg/bin>)`

Then for good measure, I reinstalled python-ffmpeg, then it worked.
