### ISSUE TITLE
There is no possibility to set the same command line argument more than one time

### ISSUE THREAD

**Issue by akustovbanuba** [kkroening/ffmpeg-python#158]
For example I couldn't call **ffmpeg** this way:
`ffmpeg -i INPUT -map_channel 0.0.1 -map_channel 0.0.0 OUTPUT`
As the result there is no way to configure _map_channel_.

**Comment by xiaclo** [comment]
Yeah there is, but it's hacky.

```python
class DuplicateString(str):
    def __hash__(self):
        return hash(self + str(id(self)))

ffmpeg.input(INPUT).output(OUTPUT, **{
    DuplicateString('map_channel'): '0.0.1',
    DuplicateString('map_channel'): '0.0.0',
})
```

I agree there should be a better way, but python has workarounds for everything.
