### ISSUE TITLE
Is there a way to get certain frames like i frame, b frame and p frame?

### ISSUE THREAD

**Issue by SystemErrorWang** [kkroening/ffmpeg-python#164]
Hello kkroening, thank you for sharing this project. I would like to know if there's a way to get certain frame, such i frame, p frame and b frame from the video? thank you again for your kind help.

**Comment by kkroening** [comment]
I don't know what `i`, `p` and `b` are referring to, or if you're just using those as arbitrary frame numbers, but take a look at the [examples](https://github.com/kkroening/ffmpeg-python/tree/master/examples#read-single-video-frame-as-jpeg-through-pipe) to see how to read individual frames (look for "Read single video frame").

**Comment by 153957** [comment]
I think they meant the different frame types used in compressed video formats: https://en.wikipedia.org/wiki/Video_compression_picture_types
When the videos were created using fixed key-frame rates you might be able to select specific frames, as shown in the examples, to get those i frames.
