### ISSUE TITLE
ffmpeg.global_args() not implemented?

### ISSUE THREAD

**Issue by reformstudios** [kkroening/ffmpeg-python#170]
Hi there,
Thanks for sharing this great tool.

I was going to try this method to add '-y' argument (before I noticed you already had a specific overwrite_output() method which works), but it doesn't appear to be implemented.
ffmpeg.global_args() is not implemented

Calling this via : 
stream.global_args(stream, 'y', 'progress', 'loglevel', 0)
or 
stream.global_args('y', 'progress', 'loglevel', 0)
has no affect on the result of stream.get_args() and the arguments seem not to get passed to ffmpeg either.

Also, this form of supplying arguments doesn't seem to be valid either.
stream.global_args(**{'loglevel':0})

I would expect it to take the same form as input and output nodes, eg (stream, *args, **kwargs) ?

I you can confirm that my understanding of these limitations is correct then if I have time I may be able to contribute to implement these features.

Thanks!

**Comment by xiaclo** [comment]
global_args is only applicable to an output (before run), and takes a list of args, not kwargs.

Something like `stream.global_args('-y', '-progress', '-loglevel', '0')` should work if applied just before `run()`

**Comment by reformstudios** [comment]
Ah I must have been doing it wrong! Thanks for explaining that for me.
Cheers
p.
