### ISSUE TITLE
read input at native frame rate (-re)

### ISSUE THREAD

**Issue by creimers** [kkroening/ffmpeg-python#176]
Is there a way to specify the `-re` option (read input at native frame rate) that usually comes *before* the input option?

**Comment by zimka** [comment]
@creimers Have seen authors answer somewhere in issues earlier, it works for me:
`cmd = ffmpeg.input(input_name, re=None).output(final_name, c='copy')`
`print(cmd.compile())`

**Comment by kkroening** [comment]
Relates to #218 (marked as enhancement to update docs and support `=True` as well).
