### ISSUE TITLE
How to use hstack filter

### ISSUE THREAD

**Issue by mseise123** [kkroening/ffmpeg-python#177]
I try to use the hstack filter to show videos side by side, but I do not see how to handle this here. 
The ffmpeg command line should look like (see https://stackoverflow.com/questions/35349935/ffmpeg-crop-with-side-by-side-merge)

ffmpeg -i input0 -i input1 -filter_complex \
"[0:v]crop=iw/2:ih:0:0[left]; \
 [1:v]crop=iw/2:ih:ow:0[right]; \
 [left][right]hstack" output

Thanks for your help

**Comment by kkroening** [comment]
Something like this:
```python
in0 = ffmpeg.input('input0').crop(...)
in1 = ffmpeg.input('input1').crop(...)
out = ffmpeg.filter([in0, in1], 'hstack').output('output')
```

Refer to the examples and API docs for more info.
