### ISSUE TITLE
Merge .mp4 and .mp3 files

### ISSUE THREAD

**Issue by salabim** [kkroening/ffmpeg-python#182]
I am trying to merge an .mp4 file with a .mp3 file. On the command line, that's easy, by just using two -i specifiers.
However when I make to infiles, like
infile1 = ffmpeg.inout("video.mp4")
infile2 = ffmpeg.input("sound.mp3")
and then
(ffmpeg.concat(infile1, infile2).output("merged.mp4")
I get an error:
Stream specifier '' in filtergraph description [0)[1]concat=n=2[s0] matches no stream.

Is this possible at all? And if so, how?

**Comment by rsomani95** [comment]
Try 

```python
infile1 = ffmpeg.input("video.mp4")
infile2 = ffmpeg.input("sound.mp3")

merged  = ffmpeg.concat(infile1, infile2, v=1, a=1)
output  = ffmpeg.output(merged[0], merged[1], "merged.mp4")
```
