### ISSUE TITLE
Graph visualization

### ISSUE THREAD

**Issue by kkroening** [kkroening/ffmpeg-python#19]
Finish code from #17 for visualizing graphs.

Basically just need to determine the right way to handle import errors for `graphviz`, since I don't want `graphviz` to be a requirement for `ffmpeg-python`.

**Comment by Depaulicious** [comment]
```python
try:
    import
except ImportError:
    doStuff()
```
?

**Comment by Depaulicious** [comment]
Or you can put everything in a module named something like `_view`, then in the `view` module simply do `from ._view import *` in a try except.

This would be a cleaner solution, probably.

**Comment by kkroening** [comment]
Yeah good ideas. I moved the `import graphviz` into the body of the `view()` function - that way it doesn't even attempt to import `graphviz` until it really needs it, and then fails with a helpful error message if it's unavailable.

See #21

**Comment by kkroening** [comment]
Merged #18.
