### ISSUE TITLE
How can you pipe the output to ffplay?

### ISSUE THREAD

**Issue by oveddan** [kkroening/ffmpeg-python#190]
Is there a way to pipe the output live to ffplay so it can be viewed immediately?

**Comment by kkroening** [comment]
Something like this:
```python
import ffmpeg
import subprocess

in_filename = 'in1.mp4'

probe = ffmpeg.probe(in_filename)
video_stream = next((stream for stream in probe['streams'] if stream['codec_type'] == 'video'), None)
width = int(video_stream['width'])
height = int(video_stream['height'])

process1 = (
    ffmpeg
    .input(in_filename)  # (or whatever)
    # (filters/etc. go here)
    .output('pipe:', format='rawvideo', pix_fmt='rgb24')
    .run_async(pipe_stdout=True)
)
process2 = subprocess.Popen(
    [
        'ffplay',
        '-f', 'rawvideo',
        '-pix_fmt', 'rgb24',
        '-s', '{}x{}'.format(width, height),
        '-i', 'pipe:',
    ],
    stdin=process1.stdout,
)
process1.wait()
process2.wait()
```

**Comment by NiccoloGranieri** [comment]
@kkroening thanks so much for this! I wanted to ask a question related to the code above:

If I implement any kind of filtering in the section you marked with:  # (filters/etc. go here) I seem to be unable to live affect the args given to the filters. So if for example blur the image by calling:

`.filter('gblur', sigma=blurIndex)`

and I try to increment blur index in time only the first value seems to affect the video. Do you know if it's even possible to affect the filter parameters live?

**Comment by kkroening** [comment]
>  Do you know if it's even possible to affect the filter parameters live?

There is no way that I know of to change ffmpeg filter graphs dynamically.
