### ISSUE TITLE
The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.

### ISSUE THREAD

**Issue by MaJian8** [kkroening/ffmpeg-python#206]
import ffmpeg

def add_audio_in_video(audio, video):
        v = ffmpeg.input(video)
        a = ffmpeg.input(audio)
        out = ffmpeg.output(v, a)
        out.run()

if __name__ == '__main__':
        a = 'video_with_audio.mp3'
        v = 'first_part.mp4'
        add_audio_in_video(a, v)

The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.

How can I fix it? Thx :)

**Comment by MaJian8** [comment]
I run:
out = ffmpeg.output(v, a, 'out.mp4', ac = 2)
It does not work.

**Comment by MaJian8** [comment]
out = ffmpeg.output(v, a, 'out.mp4', strict='-2')

It works!

**Comment by kkroening** [comment]
Thanks @MaJian8. Marking as resolved and closing.

**Comment by swerizwan** [comment]
add -strict -2 in cmd

cmd = 'ffmpeg -r 30 -i "{}" -i "{}" -pix_fmt yuv420p -strict -2 -s 512x768 "{}" -y'.format(image_temp, args.wav_path, output_path)
