### ISSUE TITLE
How to specify multiple output?

### ISSUE THREAD

**Issue by xukefang** [kkroening/ffmpeg-python#211]
How can I get jpeg images along with segments at one commands?

like this:
ffmpeg -i xxx  -f image2 xxx%d.jpg -f segment -segment_time xx -segment_format mp4 xxx%d.mp4

**Comment by xukefang** [comment]
I solved this issue by 'global_args'

**Comment by h3ct0r** [comment]
@xukefang can you share a working snippet? Thanks!

**Comment by 153957** [comment]
```python
split_input = input.split()
split_input[0].output('version1.mp4', …)
split_input[1].filter(…).output('version2.mp4', …)
```

**Comment by h3ct0r** [comment]
Thank you @153957 ! Do you have an example of use this multiple output with segments? Such as `-f segment -segment_time xx -segment_format mp4 xxx%d.mp4`?

**Comment by abhyuditjain** [comment]
@153957 How do you run that?

```
>>> inp = ffmpeg.input('song.mp3')>>> split_input = inp.split()>>> for i, v in enumerate(['32k', '64k', '128k', '320k']):...     split_input[i].output('song_%s.mp3' % v, **{'b:a': v})... 
output(b:a='32k', filename='song_32k.mp3')[None] <6343ee722a1b>
output(b:a='64k', filename='song_64k.mp3')[None] <4fa08c1c0919>
output(b:a='128k', filename='song_128k.mp3')[None] <859942853b64>
output(b:a='320k', filename='song_320k.mp3')[None] <1b9d7c7ebbfc>
```

I don't know how too actually run it as no files are being created.

**Comment by 153957** [comment]
@abhyuditjain I usually do it like this:
```python
split_input = input.split()
output = ffmpeg.merge_outputs(
    split_input[0].output('version1.mp4', …),
    split_input[1].filter(…).output('version2.mp4', …),
)
output.run()
```
But maybe you can also just call `.run()` on each of those individually, but for performance it is probably better to use merge_outputs.

**Comment by 153957** [comment]
@h3ct0r I would not be certain how that works, maybe @kkroening could help with that.
