### ISSUE TITLE
how to use codec and threads ?

### ISSUE THREAD

**Issue by maaiika** [kkroening/ffmpeg-python#216]
ffmpeg  -y -threads 16 -i input.mp4 -c:v h264_qsv -vf "ass=a.ass" o.mp4
import ffmpeg
(
    ffmpeg
    .input('input.mp4')
    .filter_('subtitles', 'a.ass')
    .output('o.mp4')
    .run()
)
how to use codec(-c:v) and threads ?

**Comment by kkroening** [comment]
Take a look at the ["Special option names" example in the readme](https://github.com/kkroening/ffmpeg-python#custom-filters).
