### ISSUE TITLE
python invoke ffmpeg.probe get error

### ISSUE THREAD

**Issue by rarest** [kkroening/ffmpeg-python#224]
Hi:
python invoke ffmpeg.probe get error
[Errno 2] No such file or directory: 'ffprobe': 'ffprobe'
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
 in 
     15 
     16 video_path = "VID20100130074151.mp4"
---> 17 rotateCode = check_rotation(video_path)

 in check_rotation(path_video_file)
      4 
      5 def check_rotation(path_video_file):
----> 6     print(ffmpeg.probe(path_video_file)['format']['duration'])
      7     meta_dict = ffmpeg.probe(path_video_file)
      8     print(meta_dict)

/usr/local/lib/python3.7/site-packages/ffmpeg/_probe.py in probe(filename, cmd, **kwargs)
     18     args += [filename]
     19 
---> 20     p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
     21     out, err = p.communicate()
     22     if p.returncode != 0:

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    767                                 c2pread, c2pwrite,
    768                                 errread, errwrite,
--> 769                                 restore_signals, start_new_session)
    770         except:
    771             # Cleanup if the child failed starting.

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1514                         if errno_num == errno.ENOENT:
   1515                             err_msg += ': ' + repr(err_filename)
-> 1516                     raise child_exception_type(errno_num, err_msg, err_filename)
   1517                 raise child_exception_type(err_msg)
   1518 

FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe': 'ffprobe'

**Comment by kkroening** [comment]
Make sure FFprobe is installed (e.g. by typing `ffprobe` at a shell/terminal). ffmpeg-python doesn't try to install FFmpeg/FFprobe as it is merely a wrapper.
