### ISSUE TITLE
How to add watermark and timecode by using ffmpeg-python?

### ISSUE THREAD

**Issue by retrfy** [kkroening/ffmpeg-python#225]
the ffpeg cmd  as follows
1.add watermark:
ffmpeg -i input.mp4 -vf drawtext="fontfile=simhei.ttf: text=qwer:x=10:y=10:fontsize=24:fontcolor=white" output.mp4

2.add timecode:
ffmpeg -i input.mp4 -vf drawtext="fontfile=simhei.ttf:timecode='00\:00\:00\:00':rate=30:x=10:y=10:text=Hello:fontsize=24:fontcolor=white" output.mp4

thx

**Comment by 153957** [comment]
Watermarks can be added like this:
```
(
    ffmpeg
    .input(…)
    .drawtext(text='qwer', fontsize=24, y=10, x=10, fontfile='/path/to/font/simhei.ttf', fontcolor='white')
    …
)
```
