### ISSUE TITLE
It seems the output video is mute

### ISSUE THREAD

**Issue by retrfy** [kkroening/ffmpeg-python#229]
(
    ffmpeg
    .input(r'2.mp4')
    .drawtext(text='qwer', fontsize=28, y=10, x=10, fontfile='/path/to/font/simhei.ttf', fontcolor='white')
    .output(r'3.mp4')
    .run()
)

**Comment by kkroening** [comment]
See the FAQ: https://github.com/kkroening/ffmpeg-python/blob/master/README.md#frequently-asked-questions

**Comment by abubelinha** [comment]
@retrfy how did you solve this in Python?
