### ISSUE TITLE
ffmpeg python not working

### ISSUE THREAD

**Issue by sunil1239** [kkroening/ffmpeg-python#240]
`  File "F:\Python softwares\QtMpeg\virtualenv\lib\site-packages\ffmpeg\_run.py", line 320, in run
    overwrite_output=overwrite_output,
  File "F:\Python softwares\QtMpeg\virtualenv\lib\site-packages\ffmpeg\_run.py", line 285, in run_async
    args, stdin=stdin_stream, stdout=stdout_stream, stderr=stderr_stream
  File "C:\Python34\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

I'm getting this error when I try to run the default code provided in Readme file. I'm using Python 3.6 in windows 10. Am I doing anything wrong?

**Comment by sunil1239** [comment]
Got the way to work as I missed adding or installed the ffmpeg path to the windows ffmpeg CLI path

**Comment by sakalu** [comment]
> Got the way to work as I missed adding or installed the ffmpeg path to the windows ffmpeg CLI path

I have the same issue. Could you please show me how to add the ffmpeg path? Thanks!
