### ISSUE TITLE
Sample rate (-ar) option

### ISSUE THREAD

**Issue by HeyItsUltra** [kkroening/ffmpeg-python#28]
Could we have a sample rate option to modify the sample rate of the output file?

eg. Converting a 48000kHz audio file to 44100kHz.
`ffmpeg.input('in.mp4').encode_(samplerate=44100).output('out.mp4).run()`

**Comment by kkroening** [comment]
This should do the trick:
```
ffmpeg.input('in.mp4').output('out.mp4', ar=44100).run()
```

**Comment by kkroening** [comment]
Closing. Let me know if you run into issues.
