### ISSUE TITLE
complex filter only?

### ISSUE THREAD

**Issue by dshlai** [kkroening/ffmpeg-python#29]
Hi! 

First, this is a great project for compose complex filter graph. 

For my current use (generating thumbnail from video) the project does not support option like -ss or -vf
( I was doing -vf 'select=eq(n/,999)  or -ss '55.00''

the filter_() methods seems to output complex filter only?

**Comment by dshlai** [comment]
Maybe I can implement some of the 'option' methods in '_ffmpeg.py' module?

**Comment by kkroening** [comment]
`-ss` should probably be implemented as a parameter in `input` and/or `output`:
```python
(ffmpeg
    .input('in.mp4', seek=123.0)
    # ...
    .output('out.mp4', seek=456.0)
    # ...
)
```
See [Combined Seeking](https://trac.ffmpeg.org/wiki/Seeking#Combinedseeking)

> Maybe I can implement some of the 'option' methods in '_ffmpeg.py' module?

Go for it! Pull requests are welcome.

`filter_` should work for `select`:
```python
(ffmpeg
    .input('in.mp4')
    .filter_('select', 'eq(n/,999)')
    .output('out.mp4')
    # ...
)
```

> the filter_() methods seems to output complex filter only?

That's correct. I haven't seen any reason to output `-vf`. What advantage would there be to support it?

**Comment by dshlai** [comment]
-vf is really a short hand for a single input/output video filter, how would I be able to accomplish that with _filter?

**Comment by kkroening** [comment]
```python
(ffmpeg
    .input('in.mp4')
    .filter_('somefilter', ...)
    .filter_('someotherfilter', ...)
    .filter_('yetanotherfilter', ...)
    ...
    .output('out.mp4')
)
```
All of those filters are single-input/single-output, yes?

**Comment by kkroening** [comment]
As far as I'm aware, `filter_complex` is strictly more powerful than `vf`, so there isn't any reason to use `vf` other than for the command-line arguments to be slightly shorter.

**Comment by dshlai** [comment]
how about -ss, this can go before -i (aka, as a input option for faster seeking), so this is not strictly a filter

**Comment by kkroening** [comment]
See the comment I posted above:
```
-ss can be specified in input and/or output:

(ffmpeg
    .input('in.mp4', ss='12:34')
    # ...
    .output('out.mp4', ss='56:78')
    # ...
)
```

**Comment by kkroening** [comment]
I edited the comment after I posted it, so might need to refresh.

**Comment by dshlai** [comment]
Yet, I think I am going get a crack at it when I got time this week.

**Comment by dshlai** [comment]
ok, this works, no -vf needed. Thanks.
