### ISSUE TITLE
[Question] How can I tell ffmpeg-python to look for ffmpeg in a specific place?

### ISSUE THREAD

**Issue by DinRigtigeFar** [kkroening/ffmpeg-python#297]
Hi
Sorry for the noob question, but I can't for the life of me figure out how to specify where ffmpeg-python should look for ffmpeg.
I build a youtube downloader that can take intervals and I'm trying to use pyinstaller to create an app for my friend. When running the script it works like a charm, but after having used pyinstaller to bundle the script it fails because it can't find ffmpeg.
So how can I change that?

Thanks in advance

**Comment by DinRigtigeFar** [comment]
I found the solution after some sleep.
When running the program use: run(cmd="path_to_ffmpeg")

I hope this will help others who where also sleep deprived.

**Comment by hahahaprince** [comment]
@DinRigtigeFar 
Can you explain your solution in detail?  Thank you!

**Comment by DinRigtigeFar** [comment]
> @DinRigtigeFar 
> 
> Can you explain your solution in detail?  Thank you!

Sure:
Download ffmpeg binaries and put them in your program folder. Then point the run command to the binary in that folder:
`/my/program/folder/with/ffmpeg`
Then when doing your ffmpeg thing put this inside the run command:
`run(cmd=‘/my/program/folder/with/ffmpeg’)`

**Comment by TheMrRandomDude** [comment]
@DinRigtigeFar Hi there. Sorry for pinging you again, this is going to sound a bit stupid, but, could you please link to the binaries you're referring to? Do you mean the standard ffmpeg binaries from the ffmpeg project, or the ffmpeg-python binaries?

Which ones exactly? (as in, where are they downloaded from?)

**Comment by DinRigtigeFar** [comment]
> @DinRigtigeFar Hi there. Sorry for pinging you again, this is going to sound a bit stupid, but, could you please link to the binaries you're referring to? Do you mean the standard ffmpeg binaries from the ffmpeg project, or the ffmpeg-python binaries?
> 
> Which ones exactly? (as in, where are they downloaded from?)

The standard ffmpeg binaries from the ffmpeg project 😅😊
I got them from [here](https://ffbinaries.com/downloads).
