### ISSUE TITLE
Pipe numpy image to h264 video

### ISSUE THREAD

**Issue by sgjava** [kkroening/ffmpeg-python#301]
I'm looking for example code that will take a numpy image and write it to a h264 pipe. I see the example of writing to a numpy framebuffer as output. The pipe would be called by OpenCV processing code to save a frame at a time.

**Comment by sgjava** [comment]
OK, fiddling around I came up wit this from tensorflow example, but color looks off. I'll play with that, but this works:
`#!/usr/bin/env python
import logging, sys, time, cv2, ffmpeg, numpy

logger = logging.getLogger("Writer")
logger.setLevel("INFO")
formatter = logging.Formatter("%(asctime)s %(levelname)-8s %(module)s %(message)s")
handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(formatter)
logger.addHandler(handler)
videoCapture = cv2.VideoCapture('/home/servadmin/Downloads/motion-11-55-41.avi')
process = (
    ffmpeg
    .input('pipe:', format='rawvideo', pix_fmt='rgb24', s='{}x{}'.format(1280, 720))
    .output('output/out.mp4', vcodec='h264', pix_fmt='nv21', **{'b:v': 2000000})
    .overwrite_output()
    .run_async(pipe_stdin=True)
)
lastFrame = False
frames = 0
start = time.time()
while not lastFrame:
    ret, image = videoCapture.read()
    if ret:
        process.stdin.write(
            image
            .astype(numpy.uint8)
            .tobytes()
        )        
        frames += 1
    else:
        lastFrame = True
elapsed = time.time() - start
logger.info("%d frames" % frames)
logger.info("%4.1f FPS, elapsed time: %4.2f seconds" % (frames / elapsed, elapsed))
del videoCapture`

**Comment by pderian** [comment]
Colors could be off because OpenCv's VideoCapture outputs images in BGR
format, while your ffmpeg input is 'rgb24'. If you change the latter to
'bgr24' it may fix your problem.

**Comment by sgjava** [comment]
Yes, I just fixed that, thanks! The final result:
```#!/usr/bin/env python
import logging, sys, time, cv2, ffmpeg, numpy

logger = logging.getLogger("Writer")
logger.setLevel("INFO")
formatter = logging.Formatter("%(asctime)s %(levelname)-8s %(module)s %(message)s")
handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(formatter)
logger.addHandler(handler)
videoCapture = cv2.VideoCapture('/home/servadmin/Downloads/motion-11-55-41.avi')
process = (
    ffmpeg
    .input('pipe:', format='rawvideo', pix_fmt='bgr24', s='{}x{}'.format(int(videoCapture.get(cv2.CAP_PROP_FRAME_WIDTH)), int(videoCapture.get(cv2.CAP_PROP_FRAME_HEIGHT))))
    .output('output/out.mp4', vcodec='h264', pix_fmt='nv21', **{'b:v': 2000000})
    .overwrite_output()
    .run_async(pipe_stdin=True)
)
lastFrame = False
frames = 0
start = time.time()
while not lastFrame:
    ret, image = videoCapture.read()
    if ret:
        process.stdin.write(
            image
            .astype(numpy.uint8)
            .tobytes()
        )        
        frames += 1
    else:
        lastFrame = True
elapsed = time.time() - start
logger.info("%d frames" % frames)
logger.info("%4.1f FPS, elapsed time: %4.2f seconds" % (frames / elapsed, elapsed))
del videoCapture

**Comment by solankiharsh** [comment]
Hi, is there a possibility if someone can help me with something similar. 

This is my code: 

`
process = (
            ffmpeg
            .input('pipe:', format='rawvideo', pix_fmt='bgr24', s='{}x{}'.format(self._deeptwin.image_width, self._deeptwin.image_height))
            .output(path, pix_fmt='yuv420p', vcodec='libx264', r=25)
            .overwrite_output()
            .run_async(pipe_stdin=True)
        )
        
        for res in response:
            st = datetime.datetime.now()
            print(f'{res.status} image {res.id} rendered at {datetime.datetime.now()}')
            img = np.frombuffer(res.image, dtype=np.uint8)
            img = img.reshape((int(self._deeptwin.image_height * 1.5), self._deeptwin.image_width))
            img = cv2.cvtColor(img, cv2.COLOR_YUV2BGR_I420)
            
            for frame in img:
                start = datetime.datetime.now()
                process.stdin.write(
                    frame
                    .astype(np.uint8)
                    .tobytes()
                )
                end = datetime.datetime.now()
            stop = datetime.datetime.now()
            print(f'{res.id} conversion done at {stop-st}')
        process.stdin.close()
        process.wait()
`
What this is doing currently is generating an out.h264 file. 

What I need to achieve: I want to generate chunks of h264 frames in the following way: 1.h264, 2.h264............n.h264

Any guidance would be really appreciated and helpful. 

Thanks in advance.
