### ISSUE TITLE
input same file multiple times and get different hash

### ISSUE THREAD

**Issue by simochen** [kkroening/ffmpeg-python#337]
Following error occurred when I input same file multiple times:
`Encountered xxxx with multiple outgoing edges with same upstream label None; a `split` filter is probably required`

However, I can not use split filter because I do not know the total input times and index of a certain file (according to randomness in my program).
I was wondering that can I pass a parameter with random number to `ffmpeg.input` so that different hash is generated.

**Comment by Xiaozhuangzhuang** [comment]
use "filter_multi_output" which can be found [here](https://github.com/kkroening/ffmpeg-python/blob/master/ffmpeg/_filters.py)

**Comment by gondolio** [comment]
Hi @simochen did you manage to solve your issue?
