### ISSUE TITLE
How can we suppress ffmpeg output?

### ISSUE THREAD

**Issue by analyserdmz** [kkroening/ffmpeg-python#338]
I am trying to run multiple ffmpeg conversions at the same time by using threading. Is there a way to suppress the default output of ffmpeg when executing this:

`ffmpeg.input(listItem).output(item, vcodec='h264', acodec='aac', format='mp4').run()`

Thank you.

**Comment by ingles98** [comment]
The following code should definitely prevent the output on your main terminal unless you pipe it accordingly
```python
.run(capture_stdout=True, capture_stderr=True)
```

**Comment by analyserdmz** [comment]
> The following code should definitely prevent the output on your main terminal unless you pipe it accordingly
> 
> ```python
> .run(capture_stdout=True, capture_stderr=True)
> ```

This is exactly what I am looking for. Thank you so much @ingles98
