### ISSUE TITLE
Run non-interactively

### ISSUE THREAD

**Issue by dmitrybelyakov** [kkroening/ffmpeg-python#34]
Currently ffmpeg will ask you questions, which freezes the process while it waits for response. That makes it problematic to use on the web.

**Comment by Depaulicious** [comment]
If the question ffmpeg is asking is if you want to overwrite the output, you can pass `overwrite_output=True` to  `get_args` or `run`.

https://github.com/kkroening/ffmpeg-python/blob/7669492575141c13b63fd89dde8b44ecf6bf31cb/ffmpeg/_run.py#L112-L115

https://github.com/kkroening/ffmpeg-python/blob/7669492575141c13b63fd89dde8b44ecf6bf31cb/ffmpeg/_run.py#L135-L140

You can pass any other options to `ffmpeg` by changing the `cmd` argument.

Check [`subprocess`](https://docs.python.org/3.6/library/subprocess.html) documentation.

**Comment by kkroening** [comment]
@dmitrybelyakov Depaulicious is right - adding `overwrite_output=True` makes the prompt go away.

Perhaps it should be the default rather than having to explicitly say `overwrite_output=True`. What do you think, @dmitrybelyakov?

**Comment by dmitrybelyakov** [comment]
@kkroening makes sense, yes.

**Comment by dmitrybelyakov** [comment]
@Depaulicious thanks, will do that.

**Comment by Depaulicious** [comment]
@kkroening I think the default should be `True`, but there should be a way to turn it off (e.g. `overwrite_files=False`, `-n` is added to the command line, `=None` nothing is added to the command line — `ffmpeg` will expect interaction).

It should never be interactive unless explicitly requested.

**Comment by kkroening** [comment]
> It should never be interactive unless explicitly requested.

Agreed. I'll make the change. Thanks for the input, guys.

**Comment by kkroening** [comment]
#34 fixes this. I'll close this issue for now. Feel free to add comments on #34.
