### ISSUE TITLE
could I get the key frame of the video?

### ISSUE THREAD

**Issue by ucas010** [kkroening/ffmpeg-python#344]
hi,dear
I just wonder how to get the key frame with the best project,
any suggestion or advice will be good.
thx,

**Comment by shawn-tian** [comment]
there is a way to extract the key frame index using ffprobe and then read the key frames using opencv: https://stackoverflow.com/questions/42798634/extracting-keyframes-python-opencv/51666059#51666059

**Comment by ucas010** [comment]
@shawn-tian thx

**Comment by AlexanderKozhevin** [comment]
I used to do it with command like 
```
ffmpeg -i /content/inpu t/peka.mp4 -vf "select=eq(pict_type\,I)" -vsync vfr /content/selectedframes/frame-%02d.png
```
