### ISSUE TITLE
How to use w, tw, h, th in drawtext() method?

### ISSUE THREAD

**Issue by abpanchal95** [kkroening/ffmpeg-python#346]
How to use w, tw, h, th in drawtext() method? Could you please explain? I am not able to use it.

**Comment by 153957** [comment]
Example:
```
input.drawtext(text='hello world', fontsize=13, y='main_h-3*line_h', x='main_w-text_w-line_h)
```
(note `main_h` (`main_w`) is equal to `h` (`w`), same for `text_…` equal to `t…`)

**Comment by abpanchal95** [comment]
Thank man I tried the same way don't know what I forgot although thanks.

**Comment by abubelinha** [comment]
@153957 what is `input` in your example?

**Comment by 153957** [comment]
An instance of `ffmpeg.nodes.FilterNode` (e.g. using `ffmpeg.input()`)

**Comment by abubelinha** [comment]
Thanks @153957 , it worked.
