### ISSUE TITLE
Creating Multiple Outputs

### ISSUE THREAD

**Issue by shahinesi** [kkroening/ffmpeg-python#348]
```
ffmpeg -i input \
	-acodec … \
	-vcodec … \
	output1
```
```
ffmpeg -i input1\
	-acodec … -vcodec … output1 \
	-acodec … -vcodec … output2 \
	-acodec … -vcodec … output3
```

How To code?

**Comment by 153957** [comment]
I do it like this:
```python
source = ffmpeg.input(…)
split_input = source.split()
output0 = split_input[0].output(…)
output1 = split_input[1].output(…)
output2 = split_input[2].output(…)
ffmpeg.merge_outputs(output0, output1, output2).run(…)
```

(Working example: https://github.com/153957/time-lapse/blob/master/time_lapse/output.py )

**Comment by shahinesi** [comment]
> I do it like this:
> 
> ```python
> source = ffmpeg.input(…)
> split_input = source.split()
> output0 = split_input[0].output(…)
> output1 = split_input[1].output(…)
> output2 = split_input[2].output(…)
> ffmpeg.merge_outputs(output0, output1, output2).run(…)
> ```
> 
> (Working example: https://github.com/153957/time-lapse/blob/master/time_lapse/output.py )

it support run_async ???

**Comment by shahinesi** [comment]
> I do it like this:
> 
> ```python
> source = ffmpeg.input(…)
> split_input = source.split()
> output0 = split_input[0].output(…)
> output1 = split_input[1].output(…)
> output2 = split_input[2].output(…)
> ffmpeg.merge_outputs(output0, output1, output2).run(…)
> ```
> 
> (Working example: https://github.com/153957/time-lapse/blob/master/time_lapse/output.py )

[hls @ 0000015d67a5ca80] Opening 'https://Website.ir/media_slFa_157998.ts?s=J6DEE2NroDCrgH3gV6ps2A&t=1585938758' for reading
Input #0, hls, from 'https://Website.ir/playlist.m3u8?s=J6DEE2NroDCrgH3gV6ps2A&t=1585938758':
  Duration: N/A, start: 46898.409333, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 307200
    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 307200
    Stream #0:1: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv), 426x240 [SAR 1:1 DAR 71:40], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 307200
    Stream #0:2: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 307200
Automatic encoder selection failed for output stream #1:0. Default encoder for format segment (codec none) is probably disabled. Please choose an encoder manually.
Error selecting an encoder for stream 1:0
