### ISSUE TITLE
Text expansions

### ISSUE THREAD

**Issue by krzykli** [kkroening/ffmpeg-python#36]
Hey guys,

I'm trying to evaluate expression like this:
```stream.drawtext(text=r"%%{eif\\:n+%s\\:d\\:4}" % start_frame_number, ...)```
but I always get ```eif``` related errors. Something funky is going on with escaping characters in this case.

Anyone else hit that? How should I format the expression for it to work?

Thanks,
kk

**Comment by Depaulicious** [comment]
Try not to escape characters yourself, or to escape them twice. `ffmpeg-python` tries to do the escaping itself, but ffmpeg is a bit weird with strings and may want unconfortable characters escaped a couple times.

You may also need some extra escaping if you're using a shell to run it.

**Comment by krzykli** [comment]
Thanks @Depaulicious 
From my tests:
```
r"%%{eif\:n+%s\:d\:4}" - escape text False -  error: %{eif:n+0:d:4} is not known
r"%%{eif\\:n+%s\\:d\\:4}" - escape text False -  error: %{eif\} is not known
r"%%{eif\\\:n+%s\\\:d\\\:4}" - escape text False -  error: %{eif\:n+0\:d\:4} is not known
r"%%{eif\\\\:n+%s\\\\:d\\\\:4}" - escape text False -  error: %{eif\\} is not known
r"%%{eif\\\\\:n+%s\\\\\:d\\\\\:4}" - escape text False -  error: %{eif\\:n+0\\:d\\:4} is not known
```
etc

Setting `escape_text` in the drawtext call to `True` will obviously burn whatever is in quotes exactly, and we don't want that.

Anyone any ideas? Can somebody try the same thing themselves please?

**Comment by kkroening** [comment]
Is there any reason you're using the `r` prefix on your strings? I wonder if that's throwing things off. I'll try to test this, but I'd suggest taking the `r` off and seeing if that fixes it.

**Comment by kkroening** [comment]
You should generally leave `escape_text=True` (the default). If `ffmpeg-python` isn't escaping it properly, we should fix `ffmpeg-python`, because ffmpeg string escaping is a major pain and it'd be nice to have this library deal with it once and for all.

**Comment by krzykli** [comment]
Thanks @kkroening, in this particular case, whether you're using raw strings or not doesn't make much difference, the result is the same.

To fix this quickly on my side I've skipped escaping characters if there's 'eif' present in 'text' parameter value and it works perfectly with a simple `"%%{eif\:n+%s\:d\:4}" % i` expression.

**Comment by kkroening** [comment]
It works fine if you don't do put those extra `\` chars in it yourself, don't prefix it with `-r`, and do use `escape_text=False`:
```
(ffmpeg
    .input('/Users/karlk/src/ffmpeg_wrapper/ffmpeg/tests/sample_data/in1.mp4')
    .drawtext('%%{eif:n+%s:d:4}' % start_frame_number, x=0, y=0, fontfile='/Library/Fonts/Arial.ttf', escape_text=False)
    .output('out.mp4')
    .overwrite_output()
    .run()
)
```
