### ISSUE TITLE
BytesIO buffers for reading and outputing in memory objects. 

### ISSUE THREAD

**Issue by skiler07** [kkroening/ffmpeg-python#368]
Currently, I need to create a file on my machine in order to input the video into the processing graph. For example, if the video is in S3, I need to:

1. Download & Save the video
2. Input it into FFMPEG
3. Create new file
4. Output ffmpeg to this file and upload it. 

Instead, I would like to use BytesIO to keep files in memory.

**Comment by brightening-eyes** [comment]
you can''t use BytesIO directly. just create an ffmpeg process, pipe the stdin and write there from your BytesIO.
