### ISSUE TITLE
ffmpeg process stops outputting data after ~7 mins

### ISSUE THREAD

**Issue by Troffifi** [kkroening/ffmpeg-python#370]
Hi,

The following snippet of code behaves as described in the title:
self.ffmpeg_process = (
            ffmpeg
                .input(ffmpeg_input)
                # .audio
                # .filter('silenceremove')
                .output('-',
                        # vn=None,
                        format=self.ffmpeg_format,
                        acodec=self.ffmpeg_acodec,
                        ar='{}'.format(self.rate),
                        ac='{}'.format(self.channels))
                .run_async(pipe_stdout=True, pipe_stderr=True)
        )

There is no error in the console. It just stops outputting, but the script does not exit. It strangely hangs. There is no pause in the audio input I used corresponding to the time when it stops working.

On the other hand, if I use this the following code which should do the same thing, it works with no problem:
self.command = [FFMPEG_BIN,
                        '-i', ffmpeg_input,
                        '-f', self.ffmpeg_format,
                        '-acodec', self.ffmpeg_acodec,
                        '-ar', '{}'.format(self.rate),  # ouput will have 16000 Hz
                        '-ac', '{}'.format(self.channels),  # mono (set to '2' for stereo)
                        '-']
        self.pipe = sp.Popen(self.command, stdout=sp.PIPE, bufsize=10 ** 8)

Are you aware of this behaviour? Is it a bug or do I do something wrong?

Thank you!

**Comment by trifle** [comment]
Just a hint, I've come across such behavior when ffmpeg produces a lot of text output and python's stdout/stderr pipes overflow. You might have luck with reducing the verbosity or skipping text output altogether.

**Comment by Troffifi** [comment]
You are right! This was the problem. I solved it by reducing the verbosity, as I am interested in the text output. So I changed the following line ".run_async(pipe_stdout=True, pipe_stderr=True)" into ".run_async(pipe_stdout=True, pipe_stderr=False)". Thank you!

**Comment by ziudeso** [comment]
@trifle lifesaver!!!
