### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'input

### ISSUE THREAD

**Issue by sbmzhcn** [kkroening/ffmpeg-python#40]

**Comment by zachary-m** [comment]
Hello,
@Depau @sbmzhcn 
Was there a solution to this issue? 
I am trying to do the following using the library
`ffmpeg file.mp3 -ar 16000 file-16000.wav`

`import ffmpeg
i = ffmpeg.input('wav5.wav')
o = ffmpeg.output(i, 'wav5new.wav', ar=16000)
`
Gives me the following error:
`AttributeError: 'module' object has no attribute 'input`

I tried the method in the speech to text example and got the same error.

Thanks!

**Comment by kkroening** [comment]
Make sure you have `ffmpeg-python` installed first.

It's best to do this in some sort of python virtual environment, e.g.:
```bash
$ cd ffmpeg-python/examples
$ virtualenv .venv
$ source venv/bin/activate
(venv) $ pip install -r requirements.txt
(venv) $ python transcribe.py <... args ...>
```

Note that you need to do the `source venv/bin/activate` whenever you start a new shell, or use something like `virtualenvwrapper`.

Read more about `virtualenv`, `virtualenvwrapper`, and even `pipenv` (which I'm personally not a fan of) here: http://docs.python-guide.org/en/latest/dev/virtualenvs/#lower-level-virtualenv
