### ISSUE TITLE
Ffmpeg-python : copying codec from input to output stream showing error

### ISSUE THREAD

**Issue by mohdsabahat** [kkroening/ffmpeg-python#402]
I am trying to convert an MP4 file to mkv by copying the codecs .. ffmpeg equivalent is
`ffmpeg -i input.mp4 -c copy out.mkv`

I tried this using the code:

`Input='in.mp4'`
`Output=ffmpeg.output(in , 'out.mkv',acodec='copy',vcodec='copy')`

But this line is raising a Type error :

`raise TypeError(
TypeError: Expected incoming stream(s) to be of one of the following types: ffmpeg.nodes.FilterableStream; got <class 'str'>`

**Comment by schimini** [comment]
You forgot to call the input method:

```stream = ffmpeg.input('in.mp4')```

The error your getting says you passed a ```string``` instead of a ```ffmpeg.nodes.FilterableStream``` (object returned by ```input```)

**Comment by schimini** [comment]
@mohdsabahat ping

**Comment by mohdsabahat** [comment]
😞😞
I am sorry

**Comment by payalrajguru** [comment]
Did the same thing but still got error..i want to convert mp4 to H264 but throwing the same error

**Comment by schimini** [comment]
> Did the same thing but still got error..i want to convert mp4 to H264 but throwing the same error

Did you try my suggestion?

**Comment by payalrajguru** [comment]
Yes..but it is not working..so tried using subprocess and hence now working
