### ISSUE TITLE
Add the ability to stop a stream or specify a time to stream for.

### ISSUE THREAD

**Issue by jeffreydwalter** [kkroening/ffmpeg-python#41]
It would be really useful to be able to say, "I just want to stream for X seconds". Perhaps as a parameter to run()?

What is the current best practice for streaming from some random url for a fixed amount of time? Is this supported at all today?

Thanks!

**Comment by Depaulicious** [comment]
What's wrong with `.trim()`?

**Comment by jeffreydwalter** [comment]
Does trim stop a steam?

**Comment by Depaulicious** [comment]
It depends on how you use it. https://ffmpeg.org/ffmpeg-filters.html#trim

Anyway this doesn't look like `ffmpeg-python`'s duty, this is an `ffmpeg` issue. `ffmpeg-python` does not have access to information about a running stream.

The only thing it can do to *stop a stream after X seconds* is killing the process and you can do it in many ways, such as starting a timer in a separate thread, blocking the main thread for X seconds or scheduling a callback after X seconds in any asynchronous framework you're using (like twisted or py3's coroutine stuff).

**Comment by kkroening** [comment]
@jeffreydwalter The `-ss`, `-t` and `-to` options described [here](https://trac.ffmpeg.org/wiki/Seeking) (e.g. ) are available in ffmpeg-python:
```
(ffmpeg
    .input('video.mp4', ss='00:03:00', t=60)
    .output('cut.mp4')
    .run()
)
```

**Comment by jeffreydwalter** [comment]
@kkroening thanks for pointing me to those flags! -t was exactly what I was looking for.

**Comment by roman-ku** [comment]
@kkroening I cannot get the "to" option to work — is it one of the supported options by the Python library?
