### ISSUE TITLE
Convert from flv to mp4

### ISSUE THREAD

**Issue by soroushamdg** [kkroening/ffmpeg-python#426]
Hi, thanks for your great work, it really helped me out.
but I have a question and that is how can I convert a flv file to mp4 file?

**Comment by missionfloyd** [comment]
```
(
    ffmpeg
    .input('in.flv')
    .output('out.mp4')
    .run()
)
```

**Comment by sam01101** [comment]
There's already a [answer](https://superuser.com/questions/624565/ffmpeg-convert-flv-to-mp4-without-losing-quality) from Stack Exchange
