### ISSUE TITLE
Scale image

### ISSUE THREAD

**Issue by hajix** [kkroening/ffmpeg-python#434]
Hi
I need to resize an image using ffmpeg. please tell me if there is a wrapper for the following ffmpeg command?
`ffmpeg -i input.jpg -vf scale=320:240 output_320x240.png`

regards

**Comment by ljwobker** [comment]
The list of implemented "native" filters can be found in the `ffmpeg/_filters.py` source file.  (The answer is currently "no").
However, you can explicitly implement any native ffmpeg filter by passing the correct arguments to the `.filter()` directive.


Something like:

```
    freeze = (
        ffmpeg
        .input(infile)
        .filter('scale', width='320', height='240')
        .output('outfile.mp4')
    )
```

All that said, why are you using a video-focused tool to resize a single image?  It can be done, but it's an odd use case.  (If you really just want to resize images, look up ImageMagick...)

**Comment by hajix** [comment]
You are totally right. There is no other purpose but reduce dependencies and do all pre processings using ffmpeg.

Lots of thanks.
