### ISSUE TITLE
[question] timeline automation

### ISSUE THREAD

**Issue by spamatica** [kkroening/ffmpeg-python#436]
Hi guys, can't find a forum so I'll resort to a question here,
The last few days I have been pondering how to go about automating blur over a video (and possibly other effects). For instance to simulate auto focus having trouble.

Possibly I don't know the right search terms or I'm the first person wanting this ;) ...I'm having real trouble finding a tool to do this (outside a graphical video editor but that is tedious to no end). 

Now I found this project and ffmpeg supports timeline editing of certain things (I'm not exactly sure how and to what extent...)

If I put it like this, would it be possible with ffmpeg-python to automate blur such that the size is set from a sine series?
I'm leaning towards No but it'd be nice to know from the experts.
Any other ideas? :)

**Comment by cgranier** [comment]
This might be a more complicated than what you're looking for, but [this article](https://medium.com/@allanlei/blur-out-videos-with-ffmpeg-92d3dc62d069) goes into some detail about performing a dynamic blur on a video using ffmpeg filters. It might get you pointed in the right direction.

**Comment by spamatica** [comment]
Hey thanks for the reply, that looks promising! I'll go ahead and close this as it's quite far from a bug.
