### ISSUE TITLE
Run in background or asynchronously

### ISSUE THREAD

**Issue by agjunyent** [kkroening/ffmpeg-python#44]
Is there any possibility to make the ".run()" method run in background or asynchronously? Without directly using threads nor similar options (twisted, etc).

If not, is there are option to stop the ".run()" method? Or should I use threads or similar to achieve this? I want to avoid the threading because the code will run on a simple RPi.

Thanks in advance

**Comment by kkroening** [comment]
See [subprocess](https://docs.python.org/2/library/subprocess.html).
```
import subprocess
import ffmpeg

args = (ffmpeg
    .input('in.mp4')
    .output('out.mp4')
    .get_args()
)
subprocess.Popen(['ffmpeg'] + args)
```
