### ISSUE TITLE
images/frame extraction

### ISSUE THREAD

**Issue by halarhaleem** [kkroening/ffmpeg-python#441]
Hi, 

I am trying to extract images from a video both for a whole video and for specific duration of the video.  I tried to implement the commands of fffmpeg (from its documnetation) but unable to run them using ffmpeg-python package. I have already gone thgrough some related closed issues but did not succeeded while trying custom filter option. I am at beginer level and shall highly appreciate the positive resposne.

Further, some one has tagged the task of image extraction in a closed issue using open cv library.  So, I also require some comments from @kkroening on "Why ffmpeg-python in replacement of cv2".

Regards,

**Comment by ljwobker** [comment]
To get a subset of a video stream, look at the `trim` and `select` functionality in ffmpeg.  the `.trim` method is implemented in ffmpeg-python and may help. 

From https://github.com/kkroening/ffmpeg-python/issues/215, see this example.  The 'fps' filter here simply changes the output stream to one with 2 frames per second. the .output method then writes all of those frames (2/second from the original stream) to the png files with the options shown.  

If you wanted something like "take one frame per second from time=30 to time=120 of a video, you'd `trim` the stream starting at 30 seconds and ending at 120 seconds, then run it through the `fps` filter with `fps=1` to drop all but one frame per second, then use `.output` to write it.

```

try:
    (ffmpeg.input('test.mp4')
          .filter('fps', fps=2)
          .output('test/%d.png', 
                  video_bitrate='5000k',
                  s='64x64',
                  sws_flags='bilinear',
                  start_number=0)
          .run(capture_stdout=True, capture_stderr=True))
except ffmpeg.Error as e:
    print('stdout:', e.stdout.decode('utf8'))
    print('stderr:', e.stderr.decode('utf8'))
```

**Comment by halarhaleem** [comment]
> To get a subset of a video stream, look at the `trim` and `select` functionality in ffmpeg. the `.trim` method is implemented in ffmpeg-python and may help.
> 
> From #215, see this example. The 'fps' filter here simply changes the output stream to one with 2 frames per second. the .output method then writes all of those frames (2/second from the original stream) to the png files with the options shown.
> 
> If you wanted something like "**take one frame per second from time=30 to time=120 of a video**", you'd first `trim` the stream starting at 30 seconds and ending at 120 seconds, then run it through the `fps` filter with `fps=1` to drop all but one frame per second, then use `.output` to write it.
> 
> ```
> 
> try:
>     (ffmpeg.input('test.mp4')
>           .filter('fps', fps=2)
>           .output('test/%d.png', 
>                   video_bitrate='5000k',
>                   s='64x64',
>                   sws_flags='bilinear',
>                   start_number=0)
>           .run(capture_stdout=True, capture_stderr=True))
> except ffmpeg.Error as e:
>     print('stdout:', e.stdout.decode('utf8'))
>     print('stderr:', e.stderr.decode('utf8'))
> ```

Thank you for your response.
