### ISSUE TITLE
I want to run bellow mentioned command in ffmpeg-python

### ISSUE THREAD

**Issue by umair-riaz-official** [kkroening/ffmpeg-python#444]
`ffmpeg -f lavfi -i color=size=320x240:duration=10:rate=25:color=blue output.mp4`

**Comment by raulpy271** [comment]
Hi, @umair-riaz-official 

The input `color=size=320x240:duration=10:rate=25:color=blue` you can pass in the input method, and the force parameter `lavfi` as a kwarg. See the code:

```python
input_parameter = {'f': 'lavfi'}
input_lacation = 'color=size=320x240:duration=10:rate=25:color=blue'
stream = ffmpeg.input(input_location, **input_parameter)
stream = ffmpeg.output(stream, 'output.mp4')
ffmpeg.run(stream)
```

Hope this helps!

**Comment by muhammedar** [comment]
hi @raulpy271  can you please help me running this command,, I'm really stuck, Thanks in advance
`ffmpeg -f v4l2 -framerate 30 -video_size 640x480 -i /dev/video0 -f alsa -ar 11025 -i default -f mpegts  -codec:v mpeg1video -s 320x180 -b:v 160k -bf 0 -codec:a mp2 -b:a 64k -muxdelay 0.001 https://localhost:8081/stream/1Zd7atYxVTy27jbKfhGva9cKJan/one`
I manged to add those params, but still I cant add the others 
`process = (
    ffmpeg
    .input('pipe:')
    .output(url, vcodec='mpeg1video',format="mpegts",s='320x180',bitrate='160k',bf='0')
    .run_async(pipe_stdin=True)
)`
