### ISSUE TITLE
Adding general options

### ISSUE THREAD

**Issue by GitBib** [kkroening/ffmpeg-python#472]
Perhaps I missed something when studying the ffmpeg-python documentation. My question is how to add these options:

```bash
/usr/bin/ffmpeg -vaapi_device /dev/dri/renderD128 -y -i ...
```
I am attaching a drawing of the finished code

**Comment by raulpy271** [comment]
You can add global parameters using the `global_args` method. Here's an [example](https://github.com/kkroening/ffmpeg-python/tree/master/examples#stream-from-a-local-video-to-http-server) that has added the `-re` global parameter.
