### ISSUE TITLE
any chance of a 0.2.0+ release? I'm particularly interested in commit 2a7a2d78

### ISSUE THREAD

**Issue by cameron-simpson** [kkroening/ffmpeg-python#486]
I'll run off git master for the time being...

**Comment by cameron-simpson** [comment]
I'm passing multiple `-metadata` options.

**Comment by kkroening** [comment]
Sorry for the delay on getting latest master released. A 0.3.0 release will be coming shortly with the latest master changes, followed by a 1.0.0 with some substantial improvements. Thanks for your interest and patience.

**Comment by cameron-simpson** [comment]
Many thanks! - Cameron
