### ISSUE TITLE
how to combine one audio and one video?

### ISSUE THREAD

**Issue by amantiwari1** [kkroening/ffmpeg-python#506]
Help !!

```
ffmpeg.exe -i video.mp4 -i audio.m4a -c:v copy -c:a aac output.mp4
```

I have no idea how to write in python!! help

**Comment by raahii** [comment]
How about this ?

```python
video, audio = ffmpeg.input("video.mp4"), ffmpeg.input("audio.m4a")
(
    ffmpeg
        .concat(video, audio, v=1, a=1)
        .output("output.mp4")
        .run()
)
```

**Comment by amantiwari1** [comment]
@raahii  there is no aac

**Comment by wanyhamo** [comment]
> @raahii there is no aac
How about this ?
video, audio = ffmpeg.input("video.mp4"), ffmpeg.input("audio.m4a")
(
    ffmpeg
        .concat(video, audio, v=1, a=1)
        .output("output.mp4",acodec="aac")
        .run()
)

**Comment by amantiwari1** [comment]
got it!!  thank you @wanyhamo
