### ISSUE TITLE
How to drop video (-vn), audio (-an), or subtitle (-sn) stream(s)

### ISSUE THREAD

**Issue by yankee14** [kkroening/ffmpeg-python#514]
I am attempting to transcode an H265 + AAC + subtitle file to an H264 + AAC file, dropping the subtitle stream. I don't know how to tell ffmpeg-python the right kwargs equivalent to "-sn".

        # setup ffmpeg python
        stream = ffmpeg.input(src_filename, threads=9)
        stream = ffmpeg.output(stream, dest_filename, threads=9, t=30, vcodec="libx264", crf=23, preset="veryslow", acodec="copy", s="n")
        stream = ffmpeg.overwrite_output(stream)
        ffmpeg.run(stream)

I have tried variants such as
```
    s="n"
    "sn"
    scodec="n"
    scodec="none"
```

How can I do this?

While I'm at it, is there a way to tell ffmpeg-python colon notation, such as `-c:v`?

**Comment by yankee14** [comment]
I found some clues here: https://github.com/kkroening/ffmpeg-python/issues/102

It looks like it requires a shift in thinking about how to use ffmpeg. I'll try it later.

**Comment by yankee14** [comment]
I mostly solved my issue, see https://gist.github.com/yankee14/1838b4f218a6be5db3353869c94900ed

**Comment by OverSurge** [comment]
Hi, can you check if `sn=None` works ? It worked for me with `an`.

**Comment by jooola** [comment]
You can add `{vn,an}=None` on the input to remove video or audio, but I don't know regarding subtitles, probably. See below.

```python

cmd = (
    ffmpeg.input("tests/test_data/44100Hz-16bit-mono.mp3", vn=None)
    .output("/dev/null", format="null")
)

```
