### ISSUE TITLE
Play live h.264 encoded video from aiortc using ffmpeg-python

### ISSUE THREAD

**Issue by VishnuNairP** [kkroening/ffmpeg-python#519]
Hi,

I am using ffmpeg-python for a project that encodes it into h.264 and stream it using aiortc and then play it live on the other end. But I couldn't find out how I can play the stream live using ffmpeg-python on the other side.
Is this possible using ffmpeg-python?
Thanks in advance!

**Comment by raulpy271** [comment]
To play a video you should use ffplay. Its a tool that is installed when you install the FFmpeg. This library compile commands to ffmpeg instead ffplay. 

But search more, I can be wrong.

**Comment by VishnuNairP** [comment]
> To play a video you should use ffplay. Its a tool that is installed when you install the FFmpeg. This library compile commands to ffmpeg instead ffplay. 
> 
> But search more, I can be wrong.

@raulpy271 Thank you for the reply! But does this mean I can't use ffplay using the package?

**Comment by raulpy271** [comment]
Probably not. 

This library converts python commands to a command to be run in terminal calling ffmpeg.  The compiled command is in this way:

```shell
ffmpeg -i <media> -f <format> <output>
```

While using ffplay the command is different:

```shell
ffplay -f <format> <input>
```

I simplified the command to be easy to understand. But anyway, this library doesn't compile in the above way.

**Comment by VishnuNairP** [comment]
I see. I guess I'll go ahead and close the issue then. Thank you @raulpy271 !

**Comment by raulpy271** [comment]
Thanks, man! good work!

**Comment by nicomiguelino** [comment]
Hi,

Are there plans to add wrappers for `ffplay` in the future?
