### ISSUE TITLE
32bit version

### ISSUE THREAD

**Issue by sh-navid** [kkroening/ffmpeg-python#523]
Is there a official 32bit version of FFmpeg for windows users?

**Comment by raulpy271** [comment]
You should search it in the official [site](https://ffmpeg.org/) of ffmpeg, they recommend two sites to get a ffmpeg exe for windows. One of them is [it](https://github.com/BtbN/FFmpeg-Builds), which has 32 bits support.

**Comment by sh-navid** [comment]
Hi :) thanks for the response.
They said this in their README:

```
Targets, Variants and Addins
The two available targets are win64 and win32.
```

But I cannot find 32bit versions.
So I made this issue in their repo:
https://github.com/BtbN/FFmpeg-Builds/issues/61
