### ISSUE TITLE
How to pass -x256-params to output?

### ISSUE THREAD

**Issue by emepetres** [kkroening/ffmpeg-python#529]
Hi, I'd like to do something like

`ffmpeg -i input.mp4 -vcodec libx265 -x265-params lossless=1 -crf 0 -pix_fmt yuv420p output.mp4`

However, I don't know how to specify the `-x265-params` as an output argument:

```
stream = ffmpeg.output(
        stream,
        "output.mp4",
        vcodec="libx265",
        x265-params="lossless=1",  # <--- This parameter is wrong in python
        crf=0,
        pix_fmt="yuv420"
    )
```

Thanks!

**Comment by NaichuanYang** [comment]
i have the same question

**Comment by ksofiyuk** [comment]
I've found that passing `x265-params` after the `output` method through `global_args` doesn't work as intended. It seems that those options are ignored when presented after the output argument in FFmpeg, at least `.global_args('-x265-params', 'log-info=error')` doesn't change the logging level of `libx265` and it continues to produce unnecessary messages.

However, there is another option. An FFmpeg argument with a dash in its name can be passed in the following way:
```python3
ffmpeg_stream = ffmpeg_stream.output(
      output_media_path,
      codec="libx265",
      loglevel="quiet",
      **{"x265-params": "log-level=error"},
)
ffmpeg_stream.run()
```

That code successfully silences both FFmpeg and libx265.
