### ISSUE TITLE
How to load ".srt" subtitles with a video in ffmpeg-python?

### ISSUE THREAD

**Issue by mononobi** [kkroening/ffmpeg-python#530]
Is it possible to load a subtitle file with video using ffmpeg-python?

**Comment by missionfloyd** [comment]
You can load an SRT file using the [subtitles filter](https://ffmpeg.org/ffmpeg-filters.html#subtitles-1).
```python
import ffmpeg
(
    ffmpeg
    .input('input.mp4')
    .filter("subtitles", "subtitles.srt")
    .output('output.mp4')
    .run()
)
```

**Comment by mononobi** [comment]
thanks a lot

**Comment by FredyVia** [comment]
my mp4 file change to no sound by using this code
here is my output:
`
ffmpeg version 4.2.2-1ubuntu1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-3ubuntu1)
  configuration: --prefix=/usr --extra-version=1ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/fredyvia/tmp/test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:04:41.48, start: 0.000000, bitrate: 734 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 64 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 2572:2565 DAR 41152:23085], 663 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
[Parsed_subtitles_0 @ 0x564cb1977380] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
[Parsed_subtitles_0 @ 0x564cb1977380] Using font provider fontconfig
File '/home/fredyvia/tmp/res.mp4' already exists. Overwrite ? [y/N] y
Stream mapping:
  Stream #0:1 (h264) -> subtitles
  subtitles -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[Parsed_subtitles_0 @ 0x564cb1fe7340] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
[Parsed_subtitles_0 @ 0x564cb1fe7340] Using font provider fontconfig
[libx264 @ 0x564cb1908380] using SAR=2572/2565
[libx264 @ 0x564cb1908380] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x564cb1908380] profile High, level 3.1
[libx264 @ 0x564cb1908380] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=22 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/home/fredyvia/tmp/res.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 2572:2565 DAR 41152:23085], q=-1--1, 30 fps, 15360 tbn, 30 tbc (default)
    Metadata:
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
[Parsed_subtitles_0 @ 0x564cb1fe7340] fontselect: (Arial, 400, 0) -> /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf, 0, LiberationSans
[Parsed_subtitles_0 @ 0x564cb1fe7340] Glyph 0x8FD9 not found, selecting one more font for (Arial, 400, 0)
[Parsed_subtitles_0 @ 0x564cb1fe7340] fontselect: (Arial, 400, 0) -> /usr/share/fonts/opentype/noto/NotoSansCJK-DemiLight.ttc, 2, NotoSansCJKsc-DemiLight
frame= 8443 fps=163 q=-1.0 Lsize=   22514kB time=00:04:41.33 bitrate= 655.6kbits/s speed=5.43x    
video:22416kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.438551%
[libx264 @ 0x564cb1908380] frame I:38    Avg QP:16.44  size: 40048
[libx264 @ 0x564cb1908380] frame P:2476  Avg QP:20.92  size:  5608
[libx264 @ 0x564cb1908380] frame B:5929  Avg QP:22.67  size:  1273
[libx264 @ 0x564cb1908380] consecutive B-frames:  3.4%  7.7%  3.9% 85.0%
[libx264 @ 0x564cb1908380] mb I  I16..4: 29.7% 50.2% 20.1%
[libx264 @ 0x564cb1908380] mb P  I16..4:  2.9%  7.0%  0.7%  P16..4: 16.3%  4.6%  1.8%  0.0%  0.0%    skip:66.8%
[libx264 @ 0x564cb1908380] mb B  I16..4:  0.4%  0.7%  0.0%  B16..8: 16.4%  1.3%  0.1%  direct: 0.3%  skip:80.7%  L0:45.5% L1:51.9% BI: 2.7%
[libx264 @ 0x564cb1908380] 8x8 transform intra:64.0% inter:73.6%
[libx264 @ 0x564cb1908380] coded y,uvDC,uvAC intra: 25.0% 18.3% 3.0% inter: 2.3% 1.6% 0.0%
[libx264 @ 0x564cb1908380] i16 v,h,dc,p: 39% 37%  9% 15%
[libx264 @ 0x564cb1908380] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 35% 22% 26%  3%  3%  2%  5%  3%  2%
[libx264 @ 0x564cb1908380] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 33% 31% 14%  3%  4%  3%  6%  3%  3%
[libx264 @ 0x564cb1908380] i8c dc,h,v,p: 72% 14% 12%  2%
[libx264 @ 0x564cb1908380] Weighted P-Frames: Y:0.4% UV:0.1%
[libx264 @ 0x564cb1908380] ref P L0: 67.4%  9.7% 17.2%  5.7%  0.0%
[libx264 @ 0x564cb1908380] ref B L0: 85.2% 12.2%  2.6%
[libx264 @ 0x564cb1908380] ref B L1: 96.2%  3.8%
[libx264 @ 0x564cb1908380] kb/s:652.47
`

**Comment by FredyVia** [comment]
I have solved it
```
video = ffmpeg.input(inputVideoPath)
audio = video.audio
ffmpeg.concat(video.filter("subtitles", inputSrtPath), audio, v=1, a=1).output(outputVideoPath).run()
```

**Comment by robinkbr** [comment]
I receive the following error code when I try to run any of the above scripts:
UnboundLocalError: local variable 'stream_map' referenced before assignment

**Comment by ghost** [comment]
I have got here a working template with subtle graphics processing hardware requirements, you just have to make a subtitle.txt file which has all your subtitles on each newline (best of 10characters per new line). In this example, replace _**"/path/to/input_folder"**_ with the path to the folder containing your video.mp4 and **_subtitles.txt_** files. Similarly, replace _**"/path/to/output_folder"**_ with the desired path for the output video. The script will create a new video with captions at the specified output folder.
```
    from moviepy.editor import VideoFileClip, TextClip, CompositeVideoClip
    def create_video(input_folder, output_folder):
        # Load the video clip
        video_path = os.path.join(input_folder, "video.mp4")
        video_clip = VideoFileClip(video_path) 
        # Load subtitles from the subtitles.txt file
        subtitles_path = os.path.join(input_folder, "subtitles.txt")
        with open(subtitles_path, "r", encoding="utf-8") as subtitles_file:
            subtitles_lines = subtitles_file.readlines()
        # Create TextClip for each subtitle
        subtitle_clips = []
        for i, line in enumerate(subtitles_lines):
            caption_clip = TextClip(line.strip(), fontsize=24, color="yellow", bg_color="transparent")
            caption_clip = caption_clip.set_pos(("center", "bottom"))
            caption_clip = caption_clip.set_duration(video_clip.duration / len(subtitles_lines))
            caption_clip = caption_clip.set_start(i * (video_clip.duration / len(subtitles_lines)))
            subtitle_clips.append(caption_clip)
        # Combine all caption clips into a single CompositeVideoClip
        subtitles = CompositeVideoClip(subtitle_clips)
        # Overlay subtitles at the bottom of the video
        final_clip = CompositeVideoClip([video_clip, subtitles.set_pos(("center", "bottom"))])
        # Write the final video
        output_path = os.path.join(output_folder, "output_video.mp4")
        final_clip.write_videofile(output_path, codec="libx264", audio_codec="aac", fps=24)
    # Example usage:
    input_folder = "/path/to/input_folder"
    output_folder = "/path/to/output_folder"
    create_video(input_folder, output_folder) 
```

**Comment by addyuchiha** [comment]
> I have solved it
> 
> ```
> video = ffmpeg.input(inputVideoPath)
> audio = video.audio
> ffmpeg.concat(video.filter("subtitles", inputSrtPath), audio, v=1, a=1).output(outputVideoPath).run()
> ```

how can I add font to the subtitle, a .tff file?

**Comment by YuseiwithJackandCrow** [comment]
> > I have solved it
> > ```
> > video = ffmpeg.input(inputVideoPath)
> > audio = video.audio
> > ffmpeg.concat(video.filter("subtitles", inputSrtPath), audio, v=1, a=1).output(outputVideoPath).run()
> > ```
> 
> how can I add font to the subtitle, a .tff file?

You can first convert the SRT subtitles into ASS format, then adjust the ASS subtitles. After that, embed them into the MP4.

**Comment by YuseiwithJackandCrow** [comment]
if someone want to add 2 subtitles once.
use the following code:

video = ffmpeg.input(inputVideoPath)
audio = video.audio
ffmpeg.concat(video.filter("subtitles",sub1).filter("subtitles", sub2), audio, v=1, a=1).output(outputVideoPath).run()
