### ISSUE TITLE
how to add a logo use ffmpeg-python

### ISSUE THREAD

**Issue by qrpengx** [kkroening/ffmpeg-python#54]
I will to add a logo file in video file ，how to do this use ffmpeg-python

**Comment by Depaulicious** [comment]
In the readme there is sample code to overlay an image to a video:

```python
import ffmpeg

in_file = ffmpeg.input('input.mp4')
overlay_file = ffmpeg.input('overlay.png')
(ffmpeg
    .concat(
        in_file.trim(start_frame=10, end_frame=20),
        in_file.trim(start_frame=30, end_frame=40),
    )
    .overlay(overlay_file.hflip())
    .drawbox(50, 50, 120, 120, color='red', thickness=5)
    .output('out.mp4')
    .run()
)
```
As you can see you can use the `overlay` filter.

You can read `overlay`'s documentation in [ffmpeg website](https://ffmpeg.org/ffmpeg-filters.html#overlay-1)

I'm closing this as it's not an issue.
