### ISSUE TITLE
How to concat two audio files using this library?

### ISSUE THREAD

**Issue by chipzhang** [kkroening/ffmpeg-python#556]
I want to concat two audio files, the length of the output file should be the sum of the two input files. I can do this via the command:

```shell
ffmpeg -i 001.wav -i 002.wav -filter_complex '[0:a:0][1:a:0]concat=n=2:v=0:a=1[outa]' -map '[outa]' output.wav
```

How to do the same thing using this library?

Thanks!

**Comment by chipzhang** [comment]
I finally worked out this issue myself, and post the example code as a gist:

https://gist.github.com/chipzhang/877a412edd84d4b40c2631f46b203b7b

**Comment by Lcorinst** [comment]
nice guys, your codes help me a lots
