### ISSUE TITLE
Read chapters with probe

### ISSUE THREAD

**Issue by NeoCortex97** [kkroening/ffmpeg-python#560]
I wanted to use the `ffmpeg.probe()` function to read the chapters. I did not find how I could pass the `-list_chapters` flag to the probe function.

Is there a way to do that?

**Comment by swordfishwjy** [comment]
try ffmpeg.probe(filename, show_chapters=None).  
The reason is that probe() accepts **kwargs, so it has to be in "key"="value" form.

**Comment by NeoCortex97** [comment]
Thanks, but i think this is a little intuitive, at least if it is not documented prominently

**Comment by webysther** [comment]
This is issue was the docs I found about this. hehehe
