### ISSUE TITLE
Support for flags: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt

### ISSUE THREAD

**Issue by antonakv** [kkroening/ffmpeg-python#565]
Hello,

Is there way to pass parameters `-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt` to ffmpeg ?

Thank you.

Best regards,
Anton

**Comment by antonakv** [comment]
This code should work but I'm not sure if it's the best way to do

```
video = ffmpeg.filter_(video, 'avoid_negative_ts', 'make_zero')
video = ffmpeg.filter_(video, 'fflags', '+genpts+discardcorrupt')
```

**Comment by Markxy** [comment]
Was facing a similar issue. Maybe this helps someone.

I believe the following use is intended?
```python
video = ffmpeg.input("C:\\vid.mp4", fflags="+genpts+discardcorrupt", avoid_negative_ts="make_zero")
```

Generates the following args in the ffmpeg chain:
```
'-avoid_negative_ts', 'make_zero', '-fflags', '+genpts+discardcorrupt', '-i', 'C:\\vid.mp4'
```
