### ISSUE TITLE
get total number of frames

### ISSUE THREAD

**Issue by ShreshthSaxena** [kkroening/ffmpeg-python#586]
Hi. how can I get total number of frames in a video file ?
For ex, in linux this works for me : ffprobe -v error -select_streams v:0 -count_packets -show_entries stream=nb_read_packets -of csv=p=0 file.webm

**Comment by LaurensJN** [comment]
You can use the .probe command if I'm not mistaken. You can add your arguments in an args dict and add these as parameters like this:

```python
input_file = file.webm
args = {"v": "error",
        "select_streams": "v:0",
        "count_packets": None,
        "show_entries": "stream=nb_read_packets",
        "of": "csv=p=0"
        }

pb = (ffmpeg
          .probe(input_file , **args)
          )
```

I didn't check if this is exactly the code you need but it'll help you get further I hope.
