### ISSUE TITLE
Equivalent to -ss (Seeking)

### ISSUE THREAD

**Issue by LaurensJN** [kkroening/ffmpeg-python#587]
Hi, great repository! 
I was wondering if there is a way to retrieve a frame from a specific timestamp, like this: 
`ffmpeg -ss 00:15:00 -i full_movie.mp4 -vframes 1 frame00001.jpg`

It searches for the timestamp and exports that exact frame from the mp4. It's important to put the -ss before the input file, because that speeds up the process by a lot (see [Seeking](https://trac.ffmpeg.org/wiki/Seeking)).

Do you think it's possible to do such thing in ffmpeg-python?

**Comment by LaurensJN** [comment]
I solved it like this:

```python
timestamp = "00:15:00"
output_file = "frame00001.jpg"
input_file = "full_movie.mp4"

stream = ffmpeg.input(input_file)
ffmpeg.nodes.get_stream_spec_nodes(stream)[0].kwargs['ss'] = str(timestamp)

stream = stream.output(output_file, frames=1)
stream.run(overwrite_output=True)
```

Looks awful but it works. If there is any better method I'd like to here it!

**Comment by 93lemondrops** [comment]
I was looking for the same thing, but it seems when you give `ss` as kwarg for `ffmpeg.input`, it is placed in front of `-i` (by #461)


With your case, 
```
>>> stream = ffmpeg.input(input_file, ss=timestamp)
>>> stream = stream.output(output_file, frames=1)
>>> stream.compile()
['ffmpeg', '-ss', '00:15:00', '-i', 'full_movie.mp4', '-frames', '1', 'frame00001.jpg']
```

`-t` also goes in front of `-i`. I tested and the speed is fine!

**Comment by LaurensJN** [comment]
This works! Thanks
