### ISSUE TITLE
How to write frame number with drawtext

### ISSUE THREAD

**Issue by jamieparry** [kkroening/ffmpeg-python#59]
hello I'm trying to write the frame number on a video and would normally do it by `text="%{n}"` in ffmpeg
when i try that in ffmpeg-python i just get it literally written like that, with `escape_text=True` or `escape_text=False`.
so how would i actually do it? my whole command chain is this
```python
ffmpeg.input(inputz)
      .drawtext(text="%{n}",start_number=0,
            fontfile="/Users/jamieparry/PyInstaller-2.1/kivthing/dist"
            "/kivthing/kivy_install/data/fonts/DroidSans-Bold.ttf",
            fontcolor="red",x=40,y=100,timecode="00:00:00:00",timecode_rate=25,
            fontsize="64",escape_text=True)
      .output(os.path.join(folderplace,"ff_outputz",justname))
      .run(overwrite_output=True)

**Comment by Depaulicious** [comment]
Can you provide the output of `.get_args()` on the output node? (i.e. remove `.run()` and add `.get_args()`)

Please format your code properly when you submit an issue next time.

_(+1 for using Kivy 😉)_

**Comment by jamieparry** [comment]
ahaaa
after looking into it a bit more it turns out you cannot do a filenumber using "%{n}" AND a timecode in the same drawtext operation even in the normal command line ffmpeg. You have to do 2 seperate drawtext operations so it won't work with my code above as that tries to do a frame number **and** a timecode in one go. There we are, problem solved! Thankyou

**Comment by Depaulicious** [comment]
No problem. I'll close this issue.

Have a nice day.

**Comment by testerclub** [comment]
i wan to write current time on the image which split from video file ,my script as below ,but the time can‘t auto update, 
(ffmpeg
             .input(videoFile)
             .drawtext(text=f"{time()}",fontsize=64, y=100, x=100,fontcolor='white',escape_text=True)
             .output(f'{self.cur_reportPath}/%d.png',
                     s=f'{self.width}x{self.height}',
                     start_number=0)
             .run(capture_stdout=True, capture_stderr=True))

**Comment by cesarliberatoo** [comment]
Hi 
Has anyone managed how to send command %{n} correctly to ffmpeg-python in order to print framenumber?
