### ISSUE TITLE
Merge Audio and Video One Frame at a Time

### ISSUE THREAD

**Issue by ddesimio** [kkroening/ffmpeg-python#597]
I have a component that receives one packet at a time. Each packet contains 2 numpy arrrays - one each for and audio and video data for ~1/30 sec.

**Is there a way to build up an mp4 as it receives data similar to cv2.write where one frame is written at a time? cv2 does not support audio**

To try handing ffmpeg actual files I made a bunch of mp4s to append to each other (video data -> mp4 + audio data -> wav = merged single frame mp4) for each packet received but it was extremely slow - was running for 30+ minutes trying to build a 5 second video.

I have also tried building off the solution provided from another issue on here with no success: [(https://github.com/kkroening/ffmpeg-python/issues/252)]

The only way I am able to get an mp4 is waiting until all packets have been received, building an mp4 (with cv2) and wav (with soundfile) then using ffmpeg.concat but I am trying to avoid making the "temp" mp4 and wav files used in concat.

Any help would be greatly appreciated!

**Comment by mrtpk** [comment]
I'm facing a similar issue. Did you find solution to your problem?

**Comment by ddesimio** [comment]
@mrtpk unfortunately not

**Comment by jinqinn** [comment]
any update ?

**Comment by mrtpk** [comment]
Thank you for getting back to me. I found a way on Linux using named pipes. Following is the command I used:

```
    command = ['ffmpeg',
           '-re',
           '-y',
           '-f', 's16le', '-sample_rate', f'{sr}', '-channels', f'{channels}', '-i', f'{audio_pipe_name}', '-c:a', 'aac',
           '-f', 'rawvideo',
           '-vcodec', 'rawvideo',
           '-pix_fmt', 'bgr24',
           '-s', f'{width}x{height}',
           '-r', str(fps),
           '-i', f'{video_pipe_name}',
           '-c:v', 'libx264',
           '-preset', 'ultrafast',
           '-f', 'rtsp',
           '-shortest', 
           '-rtsp_transport', 'tcp',
           '-muxdelay', '0.1',
           '-bsf:v', 'dump_extra',
           rtsp_url]
```

**Comment by arxyzan** [comment]
@mrtpk Do you know how this can be converted to a Python script in `ffmpeg-python`?
