### ISSUE TITLE
No more releases or updates? 

### ISSUE THREAD

**Issue by JexPY** [kkroening/ffmpeg-python#618]
That's still one of the greatest wrappers for FFMPEG so what are your future plans?

**Comment by asperduti** [comment]
same doubt

**Comment by desbma** [comment]
It's more than 1 year since the last commit now, anybody willing to maintain a fork?

**Comment by kkroening** [comment]
Yeah, sorry for the lack of updates. I've been away for quite some time. Just getting back up to speed on this project now. Looks like a lot of issues and a number of PRs have come in, and CI seems to be broken.

Current order of priorities:
* Fix CI - ideally moving to GitHub Actions.
* Stabilize Python 2 support, and release a final Python 2 compatible version.
* Immediately drop Python 2 support after the final Python 2 release. This will probably be an ffmpeg-python 1.0.0 release.
* Triage issues and PRs.

**Comment by Franky1** [comment]
And please also update the pypi package
