### ISSUE TITLE
Error: ffmpeg error (see stderr output for detail)

### ISSUE THREAD

**Issue by dannychen87** [kkroening/ffmpeg-python#623]
I keep get this error when I want to merge my audio to my video, here is my code:

```
import ffmpeg

video = ffmpeg.input('D:/Downloads/Wadada.mp4')
audio = ffmpeg.input('‪d:/Downloads/audio.mp4')

ffmpeg.concat(video, audio, v=1, a=1).output('‪D:/Downloads/out.mp4').run()
```
Or
```
import ffmpeg

video = ffmpeg.input('D:/Downloads/Wadada.mp4')
audio = ffmpeg.input('‪D:/Downloads/audio.mp4')

out = ffmpeg.output(video, audio, '‪D:/Downloads', vcodec='copy', acodec='aac', strict='experimental')
out.run()
```

Then I got the same error:
```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_3736/1465659961.py in <module>
      5 
      6 out = ffmpeg.output(video, audio, '‪D:/Downloads', vcodec='copy', acodec='aac', strict='experimental')
----> 7 out.run()

D:\xxxx\xxx\anaconda3\lib\site-packages\ffmpeg\_run.py in run(stream_spec, cmd, capture_stdout, capture_stderr, input, quiet, overwrite_output)
    323     retcode = process.poll()
    324     if retcode:
--> 325         raise Error('ffmpeg', out, err)
    326     return out, err
    327 

Error: ffmpeg error (see stderr output for detail)
```

Where did I go wrong??

**Comment by bulingda** [comment]
What a coincidence, I have the same problem. I am calling FFmPEG-Python from a thread. Have you solved the problem?

**Comment by dannychen87** [comment]
> What a coincidence, I have the same problem. I am calling FFmPEG-Python from a thread. Have you solved the problem?

Yes, I did. But seems to be a new problem unfortunately.

I have to say it was funny how I get rid off this error. I just change the single quote, which is my habit, to double quote then code could run. But just now I tried again, the error is gone no matter single or double quote I use. I have no idea what happened yesterday.

Anyway, this code works well for small size of videos, if your video is large, 8K for example, it would be very slow and all your cpu and rom would be eat up. So far I am not sure how to optimze it.
I suggest you to run `ffmpeg` in command line instead of running code in `ffmpeg-python` especially when your video is large. 

And here it is: 
``` 
ffmpeg -i video.mp4 -i audio.mp4 -c copy output.mp4
```
**Remind**: Before you run it make sure you add `ffmpeg` path in your environment variables on Windows, or `brew install` on Mac.

**Comment by songkai19** [comment]
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\My Proj\audio-to-subtitle\Your Age.mp4':
>   Metadata:
> [Parsed_subtitles_0 @ 000001d00a060c00] Unable to open **C\:\\Users\\linki\\AppData\\Local\\Temp\\Your Age.srt**
> [AVFilterGraph @ 000001d009a22680] Error initializing filters
> Error initializing complex filters.
> Invalid argument

The path to srt file seems wrong.
