### ISSUE TITLE
Extract images from a video as numpy

### ISSUE THREAD

**Issue by srikanthsridar** [kkroening/ffmpeg-python#63]
Hello kkroening,
Is it possible to use ffmpeg extracted frames in jpg to numpy using ffmpeg-python?

**Comment by Depaulicious** [comment]
If you run `ffmpeg` manually with `subprocess` you can read from any pipe of the process.

Check [this code](https://github.com/kkroening/ffmpeg-python/blob/master/ffmpeg/tests/test_ffmpeg.py#L319) from the tests.

Note that a `.compile()` operator has been added, which returns the command line arguments ready for subprocess, i.e.:

```python
p = subprocess.Popen(out.compile(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

**Comment by srikanthsridar** [comment]
Sure thank you.Will check this and get back to you.

**Comment by srikanthsridar** [comment]
Between is it possible to mention image format as "jpg" or "png" in ffmpeg in extraction step?

**Comment by srikanthsridar** [comment]
I am able to pipe the images but the image size(file size) in RAM is more than the jpg extraction.I will be reading thousands of files so I need in compressed format like jpg.Any thoughts on this?

**Comment by Depaulicious** [comment]
You should check the ffmpeg documentation. I'm pretty sure there's an encoder for jpeg but I don't remember how it works off the top of my head.
See here if you can find anything: https://ffmpeg.org/ffmpeg-all.html

**Comment by kkroening** [comment]
Here's an example in Jupyter notebook:

<img width="775" alt="screen shot 2018-06-01 at 11 19 40 pm" src="https://user-images.githubusercontent.com/2035953/40871541-4da8967c-65f2-11e8-9c99-37faea1d5e11.png">

I'll post the notebook file in the examples soon.

**Comment by kkroening** [comment]
If you want to read individual frames as jpg:
```
def read_frame_as_jpg(in_filename, frame_num):
    out, err = (
        ffmpeg
        .input(in_filename)
        .filter_('select', 'gte(n,{})'.format(frame_num)
        .output('pipe:', vframes=1, format='image2', vcodec='mjpeg')
        .run(capture_stdout=True)
    )
    return out
```
