### ISSUE TITLE
raise Error('ffprobe', out, err) - ffmpeg._run.Error: ffprobe error (see stderr output for detail)

### ISSUE THREAD

**Issue by 411A** [kkroening/ffmpeg-python#634]
Hi
I've installed `ffmpeg` + `ffmpeg-python` correctly and the path is ok but I just can't get any info.
getting this error:
```
File "/home1/myproj/virtualenv/mainproj/3.9/lib/python3.9/site-packages/ffmpeg/_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)
```
done this:
```python
file = "./Vids/tstvid.mp4"
var= ffmpeg.probe(file)
# +
# var = ffmpeg.probe(file)['streams']
print(var)
```
just to mention, I'm accessing a Linux server using SSH from VScode, I don't have superuser rights to see version details of `ffmpeg` or update it.

📝 P.S: There was another error: `[FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe': 'ffprobe'`.
✔ [Fixed it](https://github.com/kkroening/ffmpeg-python/issues/634#issuecomment-1045961841).

**Comment by 411A** [comment]
@YH-WONG eureka! it doesn't take the relative path, you should give an **absolute path** (preferably without whitespace or you should use escape character on Linux).
```diff
- file = "./Vids/tstvid.mp4"
+ file = "/mnt/c/Users/<User>/Desktop/Project/Vids/tstvid.mp4"
```
**using ffmpeg-python**
```python
import ffmpeg
from ffmpeg import probe

file = "/mnt/c/Users/User/Desktop/Project/Vids/tstvid.mp4"
media_file = file
    pprint(ffmpeg.probe(media_file)["streams"])
```
**using subprocess**
```python
import subprocess as sp
import sys

file = "/mnt/c/Users/User/Desktop/Project/Vids/tstvid.mp4"
ffpro = sp.check_output(['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', f'{file}']).decode(sys.stdout.encoding)
    print(ffpro)
```

**Comment by YH-WONG** [comment]
@411A Thanks a lot, I've fixed the problem
