### ISSUE TITLE
Passing a number to -vsync is deprecated, use a string argument as described in the manual.

### ISSUE THREAD

**Issue by ashaheedq** [kkroening/ffmpeg-python#657]
I am using vsync argument and when I pass in the value as either integer or string I am getting the same warning message. 

Here is my code snippet:
`in_file = ffmpeg.input('../9gNRbh-cam-04-VIA-IMX390-20220325_150259.h264')
out_file = '../9gNRbh-cam-04-VIA-IMX390-20220325_150259_reproduced.h264'
(
    ffmpeg
    .concat(
        *[in_file.trim(start_frame=50, end_frame = 150), in_file.trim(start_frame=1000, end_frame=1500)]
    )
    .output(out_file, codec = 'libx264', preset = "slow", crf = 15, pix_fmt = 'yuv420p', **{'profile:v':'baseline', 'vsync':'0'})
    .overwrite_output()
    .run()
)`

**Comment by jzohrab** [comment]
This is an `ffmpeg` warning, ref https://ffmpeg.org/ffmpeg.html:

```
-vsync parameter
Video sync method.

For compatibility reasons some of the values can be specified as numbers (shown in parentheses in the following table). This is deprecated and will stop working in the future.

passthrough (0)
Each frame is passed with its timestamp from the demuxer to the muxer.
... etc.
```

If you use the specified string value, it should work with no warning, e.g. from my code I use `vfr` for the old `vsync = 2` setting:

```
        ffmpeg_cmd = (
            ffmpeg
            .input(path_to_mp3, ss=starttime_s, t=duration_s)
            .output(f.name, acodec='copy', **{'vsync':'vfr', 'loglevel':'error'})
            .overwrite_output()
        )
```
