### ISSUE TITLE
Audio filters

### ISSUE THREAD

**Issue by viotemp1** [kkroening/ffmpeg-python#672]
Hello,

Is there any way to apply audio filters too. Something like -filter:a "highpass=f=200, lowpass=f=3000"
Thanks

**Comment by 9hgg** [comment]
https://xkcd.com/979

**Comment by kanjieater** [comment]
sigh :(

**Comment by TommyHanusa** [comment]
You can apply audio filters
`currentaudiofile` is a file object made with `open()`
`outputfilename` is a string thats a valid filepath like `C:/testfile_processed.wav`

`input = ffmpeg.input(currentaudiofile.name)`
`input.audio.filter("lowpass",frequency="1500")`
`ffmpeg.output(input, outputfilename).run()`
