### ISSUE TITLE
Passing flags to ffmpeg

### ISSUE THREAD

**Issue by kishaningithub** [kkroening/ffmpeg-python#68]
I would like to pass on the following flags to ffmpeg
```
.-nostdin 
 -loglevel error
``` 
Is it possible ?
The `nostdin` flag is required because ffmpeg swallows stdin. More info [here](https://stackoverflow.com/questions/33205030/mysterious-error-with-ffmpeg-on-osx#33205173).
The `loglevel` parameter would help a lot in reducing the verbosity of the ffmpeg output

**Comment by metaphox** [comment]
I guess you just need do `ffmpeg.intput('filename', nostdin=None)`

**Comment by kishaningithub** [comment]
@metaphox Dint know that one
Also i guess passing -loglevel would be resolved when issue #30 is fixed

**Comment by Depaulicious** [comment]
@kishaningithub That's correct

**Comment by kkroening** [comment]
Done. See also #30.

**Comment by roman-ku** [comment]
For anybody that needs an example (like I did):

```Python
(
    ffmpeg
    .input(in_filename, ss=time)
    .output(out_filename, vframes=1)
    .global_args('-loglevel', 'error')
    .global_args('-y')
    .run()
)

```

**Comment by HarshavardhanK** [comment]
ffmpeg -i input.mp4 -an output.mp4

How do we do something like this using ffmpeg-python?

**Comment by kishaningithub** [comment]
@HarshavardhanK Do raise your question as a new issue for it to be seen by more people
