### ISSUE TITLE
filter_ for volumedetect

### ISSUE THREAD

**Issue by mnmistake** [kkroening/ffmpeg-python#69]
Hi everyone, really sorry I opened an issue but I'm desperate now :(, how can I use filter volumedetect 
I've been following a tutorial and I ended up with this code

    `ffmpeg
            .filter_('volumedetect')
            .input(in_filename, **input_kwargs)
            .output('-', format='s16le', acodec='pcm_s16le', ac=1, ar='16k')
            .overwrite_output()
            .compile()`

I'm really new to this so, like I saw the code and saw that filter needs a stream and as I was researching I notice that .input(in_filename) gives me that stream but how I use it here, and the argument 

  -f null

how do I add it too, I just need to get the db from de audio. Any help thanks!

**Comment by Depaulicious** [comment]
How about this?

```python
`ffmpeg
        .input(in_filename, **input_kwargs)
        .filter_('volumedetect')
        .output('-', format='s16le', acodec='pcm_s16le', ac=1, ar='16k')
        .overwrite_output()
        .compile()`
```

[FFmpeg docs](https://ffmpeg.org/ffmpeg-filters.html#volumedetect) say volumedetect takes no parameters and that the input is not modified. If you want to discard the output you can probably send it to `/dev/null`.

**Comment by mnmistake** [comment]
@Depaulicious Hey thanks for replying!, it runs now but how do I get the volume now,

**Comment by kkroening** [comment]
Take a look at [this example](https://github.com/kkroening/ffmpeg-python/blob/master/examples/split_silence.py#L50) - it seems similar to your use case. It uses a regex to parse the output. It's not perfect but probably the only real way to get the output from ffmpeg.

**Comment by byguid** [comment]
If anyone's interested in a bit simpler example.
```python
import ffmpeg
import re

def get_max_volume(filepath):
    cmd = ffmpeg.input(filepath).filter('volumedetect').output('/dev/null', format='null')
   # for some reason the output is in stderr instead of stdout
    _, err = cmd.run(capture_stderr=True)
    err = err.decode('utf-8')

    max_volume_match = re.search(r"max_volume:\s*(-?\d+(\.\d+)?) dB", err)
    if max_volume_match:
        max_volume = float(max_volume_match.group(1))
        return max_volume
    return None


path = 'input.mp4'
max_volume = get_max_volume(path)
if max_volume:
    print(max_volume)
```
