### ISSUE TITLE
Add 'alsa' audio to /dev/videoX input

### ISSUE THREAD

**Issue by agjunyent** [kkroening/ffmpeg-python#70]
I'm trying to add 'alsa' audio input to an stream from /dev/videoX device.

I can run both separately using ffmpeg-python, but I'm not able to join them in the same stream. I need to record video from /dev/videoX and audio from an 'alsa' device and stream both of them at the same time as an audio+video to a http address (I can do it with only video or only audio).

Is it possible to do this?

**Comment by Depaulicious** [comment]
It's being worked on, see #45.
My branch [`custom_depau`](https://github.com/Depaulicious/ffmpeg-python/tree/custom_depau) includes this and a few other patches.

**Comment by agjunyent** [comment]
Thanks!

While it is implemented I use this workaround:

`command = ['ffmpeg'] + ['-f'] + ['alsa'] + ['-i'] + ['hw:1,0']
input_video = ffmpeg.input('/dev/video0', format='v4l2', framerate=fps, video_size=(width, height))
output_stream = ffmpeg.output(input_video, out, r=30, vcodec='mpeg1video', acodec='mp2', f='mpegts', loglevel='quiet')
command += output_stream.get_args()	`

Not optimal but I'll wait till implemented

**Comment by kkroening** [comment]
Depau's audio support has been merged (for a while now actually).

Something like this should work:
```python
input_options = {whatever}
output_options = {whatever}
audio = ffmpeg.input('hw:0', f='alsa')
video = ffmpeg.input('/dev/videoX', **input_options)
ffmpeg.output(video, audio, 'rtmp:///live/myStream.sdp', **output_options).run()
```
