### ISSUE TITLE
Feature Request: Support stream copy

### ISSUE THREAD

**Issue by znorris** [kkroening/ffmpeg-python#71]
Being able to use the `-codec` option (with `copy` in my case) would be a nice to have. See https://ffmpeg.org/ffmpeg.html#Stream-copy for details.

**Comment by harsgak** [comment]
What is the status of this? Does the implementation of this clash with something else? 
Stream copy is quite useful when you want to just extract audio or video from the stream without reencoding and losing quality.

**Comment by 1ghost1** [comment]
It already works, 
` .output(<video_name>,
                 vcodec="copy",
                 acodec="copy ")`

**Comment by kkroening** [comment]
Thanks @1ghost1!

**Comment by harsgak** [comment]
Thanks. Couldn't figure that out from the documentation.
@kkroening Can you add some more info to the `ffmpeg.output` method in [documentation](https://kkroening.github.io/ffmpeg-python/). It seems to be capable of doing a lot but the documentation on it is scarce. I especially don't understand what is being done with the **kwargs.
