### ISSUE TITLE
Is there an actual _ffmpeg module out there?

### ISSUE THREAD

**Issue by busterbeam** [kkroening/ffmpeg-python#717]
this is just another module that utilises `subprocess` which is slower than using the c/api

**Comment by Tosh0kan** [comment]
Very good question. Would like to know that as well

**Comment by busterbeam** [comment]
@Tosh0kan I found out.  simply no.  technically yes.  ffmpeg uses libraries such as `libav` which can be used properlly in python.  `av.py`.  but I'm coming back to the conclusion that this library is the best there is and will do for video processing.  It does depend on what your going to do with video/audio but for me the speed at which `ffmpeg` extracts audio and puts it into a `numpy` array is 100x better than `av.py`.  not that `av.py` or `libav` is bad but ffmpeg does all the heavy lifting and allows you to output raw binary data into `stdout` so when using `subprocess` you get decent speeds.
