### ISSUE TITLE
Upload to static file in flask project

### ISSUE THREAD

**Issue by wanaideed** [kkroening/ffmpeg-python#72]
```
def create():
    if request.method == 'POST':
            file = request.files["video"]
            stream = ffmpeg.input(file)
            stream = ffmpeg.hflip(stream)
            stream = ffmpeg.output(stream, app.root_path + '/' + app.config['UPLOAD_FOLDER'] + '/videos/dd.mp4')
            ffmpeg.run(stream)
```

> -filter_complex: No such file or directory (error from ffmpeg)

Any solution for my problem? I try change directory and check directory before pass a path but error still same.

**Comment by Depaulicious** [comment]
I don't know exactly how Flask deals with POSTed files but I think it gives you a file-like object you can read from.
If so, you should call ffmpeg manually (i.e. `p = subprocess.Popen(stream.compile(), stdin=subprocess.PIPE)`), use stdin as input in ffmpeg (use `pipe:1` as the file name, see [this](https://ffmpeg.org/ffmpeg-protocols.html#pipe)), then write to the pipe with a loop, i.e. (code not tested)

```python
CHUNK_SIZE = 1024
data = file.read(CHUNK_SIZE)
while data:
    p.stdin.write(data)
    data = file.read(CHUNK_SIZE)
```

Check Flask's documentation to see how to stream POST data like that.

**Comment by Honghe** [comment]
Full demo:
```python
import json
import logging
import subprocess

import ffmpeg
from flask import Flask, request

app = Flask(__name__)


def save_audio(file):
    f_path = 'upload_file.wav'
    stream = ffmpeg.input('pipe:0')
    stream = ffmpeg.output(stream, f_path, acodec='pcm_s16le', ac=1, ar='16k')
    # TODO, prompt and log when overwrite
    stream = ffmpeg.overwrite_output(stream)
    p = subprocess.Popen(stream.compile(), stdin=subprocess.PIPE)
    CHUNK_SIZE = 1024
    data = file.read(CHUNK_SIZE)
    while data:
        p.stdin.write(data)
        data = file.read(CHUNK_SIZE)


@app.route("/", methods=['POST', 'GET'])
def save_and_verification_audio():
    if request.method == 'GET':
        return '''
        <!doctype html>
        <title>Upload new File</title>
        <h1>Upload new File</h1>
        <form method=post enctype=multipart/form-data>
          <input type=file name=file>
          <input type=text name=id value="bala">
          <input type=submit value=Upload>
        </form>
        '''

    task_id = request.form['id']
    # get file
    file = request.files['file']
    filename = file.filename
    save_audio(file)
    logging.info('save file: {}'.format(json.dumps({'filename': filename, 'task_id': task_id}, ensure_ascii=False)))
    return 'ok'


if __name__ == '__main__':
    app.run(debug=True)

```

**Comment by krrishdholakia** [comment]
@Honghe I tried this and i'm getting the error that 'upload_file.wav' doesn't exist. Any help/advice?

**Comment by Honghe** [comment]
@krrishdholakia Do you have the write permission of the target directory?

**Comment by krrishdholakia** [comment]
where do i set that ? i'm running this on a heroku instance

**Comment by krrishdholakia** [comment]
@Honghe here's the error i got from the subprocess call: 

`ValueError: write to closed file`

i think it's referencing the 'upload_file.wav', but i'm curious how it can be closed if it's never been written to ?

**Comment by krrishdholakia** [comment]
@Honghe Did some further digging, 

here's what i'm getting: 

`pipe:0: Invalid data found when processing input`
