### ISSUE TITLE
Support non-Python characters in node arguments

### ISSUE THREAD

**Issue by capbert** [kkroening/ffmpeg-python#73]
I am new to this great project and am very much enjoying the ease of use, especially the complex filtering api. However, it is unclear to me how to multiplex multiple inputs as so:
`ffmpeg -i audio.m4a -i video.mp4 -c:v libx264 -c:a aac output.mp4`
Is this possible with this library?

**Comment by Depaulicious** [comment]
For this particular example you can do it by creating the output stream manually, i.e.

```python
i1 = ffmpeg.input("audio.mp4")
i2 = ffmpeg.input("video.mp4")
out = ffmpeg.nodes.OutputNode([i1, i2], "output", kwargs={"filename": "output.mp4", "c:v": "libx264", "c:a": "aac"}).stream()
print(" ".join(out.compile()))
```
which prints out
```
ffmpeg -i audio.mp4 -i video.mp4 -map [0] -map [1] -c:a aac -c:v libx264 output.mp4
```
(I haven't tested it and I'm not 100% sure, but the map arguments are quite useless and are implicit in your command line)

I don't think this is the best solution though (it's an ugly workaround actually), and it should be part of what #45 does. We'll need to think of how to implement it in a more user friendly manner.
Maybe something like

```python
out = ffmpeg.output(stream, "output.mp4", normal_kwarg="test", kwargs={"kwarg-with-non-python-characters:a": "test"})
```
for every function in the API that creates a new KwargsReprNode.

**Comment by capbert** [comment]
Thank you for the suggestion. When I attempt to create the output stream manually following your suggested code, I get this error complaining about too many inputs. Can you lend any perspective?
```
>>> out = ffmpeg.nodes.OutputNode([i1, i2], "output", kwargs={"filename": "output.mp4", "c:v": "libx264", "c:a": "aac"}).stream()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bert/.virtualenvs/ffmpeg-test/lib/python2.7/site-packages/ffmpeg/nodes.py", line 186, in __init__
    kwargs=kwargs
  File "/Users/bert/.virtualenvs/ffmpeg-test/lib/python2.7/site-packages/ffmpeg/nodes.py", line 95, in __init__
    self.__check_input_len(stream_map, min_inputs, max_inputs)
  File "/Users/bert/.virtualenvs/ffmpeg-test/lib/python2.7/site-packages/ffmpeg/nodes.py", line 76, in __check_input_len
    raise ValueError('Expected at most {} input stream(s); got {}'.format(max_inputs, len(stream_map)))
ValueError: Expected at most 1 input stream(s); got 2
```

In terms of a higher level api, perhaps an interface similar to that of .concat() could work. I realize this is a naive example, but for the sake of sketching perhaps something like `ffmpeg.multiplex()` or `ffmpeg.merge_inputs()`:
```
i1 = ffmpeg.input("audio.mp4")
i2 = ffmpeg.input("video.mp4")
(ffmpeg
.multiplex( [ i1, i2 ], **kwargs)
.output('out.mp4', 'c:a'='aac', 'c:v'='libx264')
.run()
)
```

**Comment by Depaulicious** [comment]
That's not valid Python syntax, it can't be done like that:

```

**Comment by Depaulicious** [comment]
That's not valid Python syntax:

```
>>> def fn(**kw):
...     print(kw)
... 
>>> fn("test:kw"="something")
  File "<stdin>", line 1
SyntaxError: keyword can't be an expression
```

For the `multiplex` part: I'm probably using the wrong branch, oops.
`OutputNode` indeed does not support `-map` in [`master`](https://github.com/kkroening/ffmpeg-python/tree/master), in fact it's being worked on in #45.

**Comment by capbert** [comment]
Sorry for any misleading information. I was just trying to sketch out an idea. The **kwargs is just a pseudo code for the idea that there would/could be options associated with the method. My apologies if this could have been illustrated in a better way. I fully confess to neither being fluent with your code nor being a python ninja in general. I am, however, interested in your project and hope to see it evolve and help in anyway possible. Thanks again for the time on this.

**Comment by Depaulicious** [comment]
No problem, I think I understand what you said :)

In fact I think that's a Python limitation — if kwargs are passed as a dict with strings as the keys, why not allow programmers to use any valid string for argument keywords? I don't think that will ever change though, as it would make new code not backwards compatible.

Your use case is not currently supported, we'll keep that in mind. I'm waiting for @kkroening to review the implementation of #45, then we may go on and extend it.

**Comment by capbert** [comment]
Thank you! I will stay tuned.

**Comment by AGollapalli** [comment]
There is actually a way around this.

` **{"c:v":"libvpx-vp9"}`
is equivalent to:
`"c:v"="libvpx-vp9"`

**Comment by kkroening** [comment]
Try `output('out.mp4', acodec='aac', vcodec='libx264')`.
