### ISSUE TITLE
ffmpeg is guessing incorrect format based on -i argument

### ISSUE THREAD

**Issue by bryanstaley** [kkroening/ffmpeg-python#74]
It appears that ffmpeg is guessing the audio format incorrectly if the -f option appears after the -i option in the ffmpeg command.  The following command works:
```
ffmpeg -f s16le -ac 1 -ar 16000  -i /home/bstaley/Downloads/20160509132350369-data.raw /tmp/test3.mp3
```
Unfortunately, ffmpge-python generates the equivilant:

```
ffmpeg -i /home/bstaley/Downloads/20160509132350369-data.raw -f s16le -ac 1 -ar 16000 /tmp/test3.mp3
```
which results in:
```
[rawvideo @ 0x13ba800] Invalid pixel format.
```

Is there a way for force the placement of -f relative to -i?

**Comment by bryanstaley** [comment]
My mistake.  I had the format arguments as part of the output.  This forces format args on both input and output
```
ffmpeg.input('20160509132350369-data.wav', format='s16le', ac=1, ar='16000').output(
    '/tmp/test3.mp3', format='s16le', ac=1, ar='16000').run()
```

**Comment by kkroening** [comment]
Thanks for sharing your solution in case others run into the same issue.
