### ISSUE TITLE
Is there an orthodox way to schedule stop?

### ISSUE THREAD

**Issue by 1ghost1** [kkroening/ffmpeg-python#77]
Is there a syntactic sugar for specifying the longitude of the recorded piece, or do I have to specify it separately?

**Comment by kkroening** [comment]
Check out the `-ss`, `-t`, and `-to` ffmpeg options.
```python
(
    ffmpeg
    .input('in.mp4', ss='00:01:00')
    .output('out.mp4', to='00:02:00')
)
```

**Comment by kkroening** [comment]
https://trac.ffmpeg.org/wiki/Seeking
