### ISSUE TITLE
is there a way to extract frames as numpy arrays or pil images from a video stream?

### ISSUE THREAD

**Issue by Data-drone** [kkroening/ffmpeg-python#78]
I can't see a way to not get a file output?

**Comment by kkroening** [comment]
<img width="796" alt="screen shot 2018-06-01 at 10 54 41 pm" src="https://user-images.githubusercontent.com/2035953/40871352-d02ce96c-65ee-11e8-80ab-8f430c7c585d.png">

**Comment by kkroening** [comment]
In other words,
```python
import ffmpeg
import numpy as np

(
    ffmpeg
    .input('in.mp4')
    .output('pipe:', format='rawvideo', pix_fmt='rgb24')
    .run(capture_stdout=True)
)
video = np.frombuffer(out, np.uint8).reshape([-1, height, width, 3])
```

**Comment by hosaka** [comment]
@kkroening Hello, is it possible to do the same with video streams? I have an IP camera and I can run ffmpeg to capture frames from stdout:
```
ffmpeg -i "http://192.168.11.9/videostream.asf?user=admin&pwd=password&resolution=32" -c:v copy -an -f image2pipe -pix_fmt rgb24 -
```
From reading the _run.py:run() I can see that the subprocess waits for the ffmpeg to close, would you consider a PR with something like stream() or frames() that uses a generator to yield frames as numpy arrays?

**Comment by Sam-gege** [comment]
is there a way to convert those Numpy arrays back to video after manipulation?
