### ISSUE TITLE
How does ffmpeg-python detect ffmpeg error

### ISSUE THREAD

**Issue by kietheros** [kkroening/ffmpeg-python#781]
> 
(
            ffmpeg
            .input(in_file_path)
            .output(out_file_path, vcodec='copy', acodec='copy')
            .global_args('-loglevel', 'error')
            .overwrite_output()
            .run(capture_stdout=True, capture_stderr=True)
        )

Raise ffmpeg error. I wonder how run() detect ffmpeg error ?? By return code or reading stderr

The above ffmpeg command prints following errors when run in shell, however it still return successfull (return code 0)
>
[h264 @ 0x559ce0cb4080] left block unavailable for requested intra mode
[h264 @ 0x559ce0cb4080] error while decoding MB 0 27, bytestream 23090

**Comment by charlienewey** [comment]
`ffmpeg-python` uses a process return code:
https://github.com/kkroening/ffmpeg-python/blob/df129c7ba30aaa9ffffb81a48f53aa7253b0b4e6/ffmpeg/_run.py#L334-L338

As for why the process still returns `0` - not all errors are fatal (i.e. some are recoverable, or just not that important) - in which case `ffmpeg` will still exit with a `0` return code.

**Comment by kietheros** [comment]
> Raise ffmpeg error. I wonder how run() detect ffmpeg error ?? By return code or reading stderr

Thank for your reply !
