### ISSUE TITLE
Support setting `bitrate` for output files

### ISSUE THREAD

**Issue by harsgak** [kkroening/ffmpeg-python#80]
Simple use case :

    stream = ffmpeg.input('musicvideo.mp4')
    stream = ffmpeg.output(stream, 'musicaudio.mp3', bitrate='320k')
    ffmpeg.run(stream)

Also, consider adding an option to explicitly specify whether to use `VBR (variable-bitrate)` or `CBR (constant-bitrate)`

**Comment by kkroening** [comment]
Fixed in latest releases.

**Comment by a0s** [comment]
How to set minimum and maximum bitrate in the same time with **{'b:a': '320k'} ?
