### ISSUE TITLE
How can I using File type instead of filename?

### ISSUE THREAD

**Issue by qwIvan** [kkroening/ffmpeg-python#81]
Because my file is in memory, not in file system.

**Comment by qwIvan** [comment]
I can do that with `subprocess.Popen`
`ffmpeg = subprocess.Popen('ffmpeg -i - -f wav -acodec pcm_s16le -ar 16000 -'.split(), stdin=file,  stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)`

**Comment by kkroening** [comment]
Something like this:
```python
out, err = (ffmpeg
    .input('pipe:')
    .output('pipe:', format='wav', acodec='pcm_s16le', ar=16000)
    .run(capture_stdout=True)
)
```
