### ISSUE TITLE
Duration flag

### ISSUE THREAD

**Issue by blackjam-alex** [kkroening/ffmpeg-python#82]
I want to use the duration flag:
**-t duration**

I'm rendering a video using a .png as input, like this:

`ffmpeg -loop 1 -framerate 23.98 -t 60 -i "background.png" output.mp4`

 Is there a way to accomplish this? Thanks for the help.

**Comment by kkroening** [comment]
```python
ffmpeg.input('background.png', t=60, framerate=98, loop=1).output('output.mp4').run()
```

**Comment by blackjam-alex** [comment]
It works! 
Thank you.
