### ISSUE TITLE
Cannot use multiple inputs

### ISSUE THREAD

**Issue by AdrKacz** [kkroening/ffmpeg-python#820]
How would you send more than one inputs?

The following syntax fails:

```
(
    ffmpeg
    .input('video1.mp4')
    .input('video2.mp4')
    .filter('xfade', transition='fade', duration='1', offset='3')
    .output('output.mp4')
    .run()
)
```

Using `global_args` doesn't help.

Thank you for your help.

**Comment by mattia-lecci** [comment]
Check out [this example](https://github.com/kkroening/ffmpeg-python/tree/master/examples#mono-to-stereo-with-offsets-and-video). `ffmpeg.filter` accepts a `Stream` or `list[Stream]` as first input.
Something along these lines should work:
```python
in1 = ffmpeg.input('video1.mp4')
in2 = ffmpeg.input('video2.mp4')
(
    ffmpeg
    .filter([in1, in2], 'xfade', transition='fade', duration='1', offset='3')
    .output('output.mp4')
    .run()
)
```

**Comment by AdrKacz** [comment]
Super, that works perfectly, thank you!
