### ISSUE TITLE
Help to output RTP with native speed

### ISSUE THREAD

**Issue by haiph-dev** [kkroening/ffmpeg-python#824]
I'm newbie with ffmpeg and ffmpeg-python.

I got problem with read wav file and output RTP with native speed. ffmpeg option '-re' works as below command
`ffmpeg -re -i "temp.wav" -acodec pcm_alaw -f rtp rtp://225.0.0.1:8888`

But when I tried with ffmpeg-python with 're=True', return error as below and I have no clue, please help
```
play,_ = (
    ffmpeg
    .input('temp.wav',re=True)
    .output(format='rtp', 
            filename='rtp://225.0.0.1:8888', 
            codec='pcm_alaw')
    .run()
)
```
Input #0, wav, from 'temp.wav':
  Metadata:
    encoder         : Lavf58.45.100
  Duration: 00:00:03.90, bitrate: 64 kb/s
    Stream #0:0: Audio: pcm_alaw ([6][0][0][0] / 0x0006), 8000 Hz, mono, s16, 64 kb/s
Option re (read input at native frame rate) cannot be applied to output url True -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for output file True.
Error opening output files: Invalid argument

**Comment by mattia-lecci** [comment]
Hi, try using `ffmpeg.input('temp.wav',re=None)`.
[Source](https://github.com/kkroening/ffmpeg-python/issues/703)

**Comment by haiph-dev** [comment]
> Hi, try using `ffmpeg.input('temp.wav',re=None)`. [Source](https://github.com/kkroening/ffmpeg-python/issues/703)

It works like charm. Thank you
