### ISSUE TITLE
filter_complex should not be used for basic pipelines

### ISSUE THREAD

**Issue by egaebel** [kkroening/ffmpeg-python#84]
I'm trying to use ffmpeg-python for a very simple task, concatenating many mp3s together.
I set up my pipeline like so:

```
import ffmpeg
import os
import os.path

audio_files = sorted(os.listdir("."))[:5]
audio_inputs = list(map(lambda audio_file: ffmpeg.input(audio_file), audio_files))
ffmpeg.concat(*audio_inputs).output("concat_test.mp3").run()
```

Which produces the command:

```
ffmpeg -i "file-0" -i "file-1" -i "file2" -i "file3" -i "file4" -filter_complex [0][1][2][3][4]concat=n=5[s0] -map [s0] concat_test.mp3
```

This fails with the error message: 
Stream specifier '' in filtergraph description [0][1][2][3][4]concat=n=5[s0] matches no streams.

However if I remove the -filter_complex and -map flags then the command runs as expected.

**Comment by kkroening** [comment]
Try adding `v=0, a=1` in your `concat` call:
```python
ffmpeg.concat(v=0, a=1, *audio_inputs).output("concat_test.mp3").run()
```

Source: https://stackoverflow.com/questions/19417412/ffmpeg-concatenation-filters-stream-specifier-0-in-filtergraph-matches-no-st

> Although the error message is not very user friendly you need to tell the concat filter the number of output video streams. The default is 1 for video and 0 for audio, so it's usually a good idea to be explicit:
> ```bash
> $ ffmpeg -i OHIn.wav -i OHOut.wav -filter_complex \
>  '[0:0] [1:0] concat=n=2:v=0:a=1 [a]' -map '[a]' output.wav
> ```

**Comment by kkroening** [comment]
If you leave the `filter_complex` + `map` args out as you described, ffmpeg runs but it doesn't actually concat the files.

**Comment by egaebel** [comment]
Ah! That did it. Thanks for your help. I must have been listening to an earlier output when I thought removing those args worked.

This tool is really great by the way, I really like the fluent API.

**Comment by kkroening** [comment]
Glad to help. Enjoy!
