### ISSUE TITLE
Numpy filters

### ISSUE THREAD

**Issue by kkroening** [kkroening/ffmpeg-python#9]
It should be possible to implement custom pixel-filtering in python as in the following example:
```
from ffmpeg.nodes import operator
import ffmpeg

@operator()
def my_custom_filter(parent)
    def process_frame(frame):
        width, height = frame.shape[:2]
        for x in range(width):
            for y in range(height):
                pixel = frame[width, height, :]
                r, g, b = pixel
                pixel.flat = g, r, b  # swap red/green
    return ffmpeg.map_frames_numpy(parent, process_frame)

ffmpeg \
    .input('in.mp4') \
    .my_custom_filter() \
    .output('out.mp4') \
    .run()
```

This is a simple example of swapping red/green values using numpy but it could be as sophisticated as you want. Here are some ideas:
- render image with OpenGL shader
- process image with tensorflow and render information/overlays

The ffmpeg wrapper needs to spawn and coordinate multiple ffmpeg processes and connect their input/output streams using pipes, but should be doable.

**Comment by Depaulicious** [comment]
This is interesting, but I think it'll be complicated, won't it?

**Comment by kkroening** [comment]
Yeah I think this should be a separate library that just uses `ffmpeg-python` under the covers, actually. Could probably add an example as part of #13. Closing...
