### ISSUE TITLE
ffmpeg-python and subtitles 

### ISSUE THREAD

**Issue by catafest** [kkroening/ffmpeg-python#91]
Can the  ffmpeg-python python module work like this ? 
`ffmpeg -y -i input.mp4 -vf subtitles=text.ass input_with_subs.mp4`

**Comment by kkroening** [comment]
```python
import ffmpeg

(
    ffmpeg
    .input('input.mp4')
    .filter_('subtitles', 'text.ass')
    .output('input_with_subs.mp4')
    .overwrite_output()
    .run()
`
```

**Comment by jackforlit** [comment]
> ```python
> import ffmpeg
> 
> (
>     ffmpeg
>     .input('input.mp4')
>     .filter_('subtitles', 'text.ass')
>     .output('input_with_subs.mp4')
>     .overwrite_output()
>     .run()
> )
> ```

After running above code, there is no audio in output files...
Is there any changes in new version?
