### ISSUE TITLE
Assemble a video from sequence of frames?

### ISSUE THREAD

**Issue by denismakogon** [kkroening/ffmpeg-python#95]
It is quite useful to be able to split a video stream onto a bunch of JPEGs (or whatever).
But how can we do the exact reverse thing? I.e., having a set of JPEGs, how to build a video stream using ffmpeg-python API?

**Comment by 153957** [comment]
Use something like this:

```python
import ffmpeg

(
    ffmpeg
    .input('/path/to/jpegs/*.jpg', pattern_type='glob', framerate=25)
    .output('movie.mp4')
    .run()
)
```

**Comment by kkroening** [comment]
Thanks @153957!

Should that dictionary in `.output()` be `**{...}`?

That's a handy script though otherwise.

**Comment by 153957** [comment]
Yes you are correct, I fixed it.

Yep, I am starting to use ffmpeg to manage/compile my time-lapse movies: https://github.com/153957/time-lapse

**Comment by kkroening** [comment]
Okay I added the above snippets to the examples:

https://github.com/kkroening/ffmpeg-python/blob/master/examples/README.md#assemble-video-from-sequence-of-frames

Closing. Thanks!

**Comment by yoon28** [comment]
is it possible to directly make video from numpy array not from image files?
