### ISSUE TITLE
concat() removes audio

### ISSUE THREAD

**Issue by seanbow** [kkroening/ffmpeg-python#96]
I have two mkv files and I'm trying to concatenate them. Running the following:

    in1 = ffmpeg.input('1.mkv')
    in2 = ffmpeg.input('2.mkv')
    ffmpeg.concat(in1, in2).output('out.mp4').run()

results in the correct video but with no audio information (ffmpeg reports audio=0kB even).

Running this:

    ffmpeg.input('1.mkv').output('out.mp4').run()

successfully converts 1.mkv to an mp4 file while preserving the audio

**Comment by kkroening** [comment]
ffmpeg audio processing is actually a bit annoying in general. When using ffmpeg filtering, it requires the audio/video streams to be processed independently and then joined together at the end.

The "concat filter" section of the [Concatenate - FFmpeg](https://trac.ffmpeg.org/wiki/Concatenate) document talks about this issue, where the audio/video streams have to be explicitly specified in order for ffmpeg to keep the audio.

Take a look at the [Process audio and video simultaneously](https://github.com/kkroening/ffmpeg-python/tree/master/examples#process-audio-and-video-simultaneously) example to see how to do this with ffmpeg-python.

**Comment by kkroening** [comment]
Also note that it's possible to do the `concat protocol` approach described in that [Concatenate - FFmpeg](https://trac.ffmpeg.org/wiki/Concatenate) document as well (but only for certain file formats and no filtering allowed, etc):
```python
ffmpeg.input('concat:in1.ts|in2.ts|in3.ts').output('out.ts', c='copy').run()
```

**Comment by kkroening** [comment]
I'd like to get to the point where ffmpeg-python sees the snippets you posted and knows that you really mean for ffmpeg to hold onto the audio streams, and just do the right thing. I think it's theoretically possible, but there are likely lots of edge cases. So for now, ffmpeg-python just wraps ffmpeg as closely as possible without a lot of magic.

**Comment by kkroening** [comment]
@seanbow Did you get a chance to see if this works for you? Let me know if I should keep this open, otherwise I'll close it in the next day or two.

**Comment by CSRaghunandan** [comment]
@kkroening I tried running this:

`ffmpeg.input('concat:in1.mp4|in2.mp4!in3.mp4').output('out.mp4', c='copy').run()`

And the resulting video only contains the first file. So, concat protocol does not support mp4?

I tried running this instead to concat videos and I'm getting an error:

``` python
import ffmpeg

try:
    in1 = ffmpeg.input("0000835.mp4")
    in2 = ffmpeg.input("0000836.mp4")
    in3 = ffmpeg.input("0000837.mp4")
    joined = ffmpeg.concat(
        in1['v'], in1['a'], in2['v'], in2['a'], in3['v'], in3['a'], v=1,
        a=1, unsafe=True).node
    out = ffmpeg.output(joined[0], joined[1], "output.mp4")
    out.run()
except ffmpeg.Error as e:
    print("ffmpeg error")
    print(e)
```

**Comment by kkroening** [comment]
> concat protocol does not support mp4?

Correct. See my earlier comment about how it only supports certain file formats.

>  I tried running this instead to concat videos and I'm getting an error

Please paste the error so we can see what you're experiencing.
